#!/bin/bash
#
# Copyright (c) 2011, 2012 Joyent Inc. All rights reserved.
#

set -o xtrace

# This includes the fatal function and downloads and installs files.
source /var/svc/setup.common

echo "Finishing setup of rabbitmq zone"

# Setup .erlang.cookie symlink
if [[ ! -L /root/.erlang.cookie ]]; then
	ln -s /var/db/rabbitmq/.erlang.cookie /root/.erlang.cookie
fi

# Apply configuration from /opt/smartdc/etc/zoneconfig now
/opt/smartdc/bin/configure || fatal "Unable to configure zone."

# Fix the rabbit SMF svc method to increase max file descriptors
egrep -s ulimit /opt/local/sbin/rabbitmq-server
if [ $? != 0 ]; then
	nawk -F= '{
	    if ($1 == "SERVER_START_ARGS") {
		print $0
		printf("ulimit -n 65535\n");
	    } else {
		print $0
	    }
	}' /opt/local/sbin/rabbitmq-server >/tmp/svc.$$
	cp /tmp/svc.$$ /opt/local/sbin/rabbitmq-server

	svcadm restart rabbitmq
fi

touch /var/svc/setup_complete
echo "setup done"
(sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &

exit 0
