#!/bin/bash
#
# Copyright (c) 2011 Joyent Inc. All rights reserved.
#

set -o xtrace

if [[ ! -f /var/svc/setup.core ]]; then
    echo "Fatal: missing /var/svc/setup.core"
    exit 1
fi
source /var/svc/setup.core

echo "Finishing setup of rabbitmq zone"

# Setup .erlang.cookie symlink
if [[ ! -L /root/.erlang.cookie ]]; then
	ln -s /var/db/rabbitmq/.erlang.cookie /root/.erlang.cookie
fi

# Apply configuration from /opt/smartdc/etc/zoneconfig now
source /opt/smartdc/bin/configure.sh

touch /var/svc/setup_complete
echo "setup done"
(sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &

