.TH "sdc\-post-upgrade" "1" "January 2013" "" ""
.
.SH "NAME"
\fBsdc-post-upgrade\fR \-\- perform post-upgrade actions
.
.SH "SYNOPSIS"
\fBsdc\-post-upgrade\fR \-c
.br
\fBsdc\-post-upgrade\fR \-w
.
.SH "DESCRIPTION"
This utility is used after a headnode upgrade to perform various tasks.
.br

.SH "OPTIONS"
\fB\-c\fR               Commit the upgrade.  Following this,
                 rollback is no longer possible.  This
                 action must be done before any further
                 upgrade can be performed.  Committing the
                 upgrade frees the space used to store data
                 for a rollback and enables new features
                 that prevent a rollback.
.
.br

\fB\-w\fR               Enable write mode.
.
.br

.SH "COPYRIGHT"
sdc\-post-upgrade Copyright (c) 2013 Joyent Inc\., All rights reserved\.
