.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "SDC\-HEALTHCHECK" "1" "April 2011" "" ""
.
.SH "NAME"
\fBsdc-healthcheck\fR \-\- check the status of SDC services
.
.SH "SYNOPSIS"
\fBsdc\-healthcheck [-p] \fR
.
.SH "DESCRIPTION"
This utility will check the status of the required SDC zones and
their associated SMF services.  It will also check that the agents
are running and responding to pings\.

.SH "OPTIONS"
The options are as follows:

\fB-p\fR    Displays the information in a parseable format (no header)
.
.SH "COPYRIGHT"
sdc\-healthcheck Copyright (c) 2011 Joyent Inc\., All rights reserved\.
