.TH "sdc\-image\-sync" "1" "January 2012" "" ""
.
.SH "NAME"
\fBsdc-image-sync\fR \-\- save system changes back to the USB key
.
.SH "SYNOPSIS"
\fBsdc\-image\-sync\fR
.
.SH "DESCRIPTION"
This utility saves certain configuration and file system changes back to the
USB key and bootable image, so that they are persistent upon reboot.
Currently only the root password and resized SDC-zone package settings are
saved to the USB key configuration files.

.SH "COPYRIGHT"
sdc\-image\-sync Copyright (c) 2012, Joyent, Inc\., All rights reserved\.
