.TH "sdc\-rollback" "1" "July 2012" "" ""
.
.SH "NAME"
\fBsdc-rollback\fR \-\- rollback headnode to previous release
.
.SH "SYNOPSIS"
.br
\fBsdc\-rollback\fR
.br

.SH "DESCRIPTION"
This utility is used to rollback a headnode to the previous release after
an upgrade.  It should only be used if there is a major problem with the
upgrade and the headnode is unusable on the new release.  All new data
and configuration created after the upgrade will be lost.

.SH "COPYRIGHT"
sdc\-rollback Copyright (c) 2012 Joyent Inc\., All rights reserved\.
