.TH "sdc\-upgrade" "1" "October 2011" "" ""
.
.SH "NAME"
\fBsdc-upgrade\fR \-\- upgrade headnode or compute node
.
.SH "SYNOPSIS"
Headnode
.br
\fBsdc\-upgrade <upgrade file>\fR
.br

Compute node
.br
\fBsdc\-upgrade\fR
.
.SH "DESCRIPTION"
This utility can be used to upgrade a headnode or a compute node after the
headnode has been upgraded.  In the headnode case, an upgrade file must be
provided.

.SH "COPYRIGHT"
sdc\-upgrade Copyright (c) 2011 Joyent Inc\., All rights reserved\.
