.TH "sdc\-upgrade" "8" "February 2013" "" ""
.
.SH "NAME"
\fBsdc-upgrade\fR \-\- upgrade headnode
.
.SH "SYNOPSIS"
Headnode
.br
\fBsdc\-upgrade <upgrade file>\fR
.br

.SH "DESCRIPTION"
This utility can be used to upgrade a headnode.  An upgrade file must be
provided.

.SH "COPYRIGHT"
sdc\-upgrade Copyright (c) 2013 Joyent Inc\., All rights reserved\.
