#!/bin/bash

svcadm clear network/physical:default >/dev/null 2>&1

echo "99 finalizing pubapi zone"

app_name='pubapi'

# from zoneinit-common:
ruby_app_update_service $app_name

if [[ ! $(/usr/bin/svcs -a|grep ${app_name}-update) ]]; then
  echo "Importing '${app_name}-update' service"
  $(/usr/sbin/svccfg import /opt/local/share/smf/manifest/$app_name-update.xml)
fi

if [[  "$(/usr/bin/svcs -Ho state ${app_name}-update)" != "online"  ]]; then
  echo "Enabling '${app_name}-update' service"
  $(/usr/sbin/svcadm enable -s ${app_name}-update)
fi


#
# Call symlink_ruby (imported from 97-zoneinit-common)
#
symlink_ruby

#
# Also, from 97-zoneinit-common
#
create_jill_account

# Note these files should have been created by previous Rake task.
# If we copy these files post "gsed", everything is reset:
if [[ ! -e /opt/smartdc/pubapi/config/config.ru ]]; then
  cp /opt/smartdc/pubapi/config/config.ru.sample /opt/smartdc/pubapi/config/config.ru
fi

if [[ ! -e /opt/smartdc/pubapi/config/config.yml ]]; then
  #TODO: what should sendmail config be for production
  cat >"/opt/smartdc/pubapi/config/config.yml" <<CONFIGYML
---
development: &defaults
  name: Joyent Public API
  url: http://${PUBLIC_IP}:8080/v1
  ignore_coupons: true
  datastore:
    adapter: sqlite3
    path: development.db
  sendmail:
    sendmail_path: /opt/local/sbin/sendmail
    sendmail_arguments: '-i -t'
    to: brock@joyent.com
    from: support@joyent.com
  capi:
    url: ${CAPI_ADMIN_IP}:8080
    username: admin
    password: tot@ls3crit
  mapi:
    coal:
      url: ${MAPI_ADMIN_IP}
      username: ${MAPI_HTTP_ADMIN_USER}
      password: ${MAPI_HTTP_ADMIN_PW}
      resources:
        smartos:
          coupon: false
          repo: false
        nodejs:
          coupon: false
          repo: true
          ram: 128

staging:
  <<: *defaults

test:
  <<: *defaults

production:
  datastore:
    adapter: sqlite3
    path: db/production.db
  <<: *defaults
CONFIGYML
fi

if [[ $(ls /opt/smartdc/pubapi/gems/gems 2>/dev/null | wc -l) -eq 0 ]]; then
  echo "Unpacking frozen gems for Public API."
  (cd /opt/smartdc/pubapi; PATH=/opt/local/bin:$PATH /opt/local/bin/rake18 gems:deploy -f /opt/smartdc/pubapi/Rakefile)
fi

if [[ ! -e /opt/smartdc/pubapi/config/unicorn.smf ]]; then
  echo "Creating Public API Unicorn Manifest."
  /opt/local/bin/ruby18 -rerb -e "user='jill';group='jill';app_environment='production';application='pubapi'; working_directory='/opt/smartdc/pubapi'; puts ERB.new(File.read('/opt/smartdc/pubapi/smartdc/unicorn.smf.erb')).result" > /opt/smartdc/pubapi/config/unicorn.smf
  chown jill:jill /opt/smartdc/pubapi/config/unicorn.smf
fi

if [[ ! -e /opt/smartdc/pubapi/config/unicorn.conf ]]; then
  echo "Creating Public API Unicorn Configuration file."
  /opt/local/bin/ruby18 -rerb -e "app_port='8080'; worker_processes=1; working_directory='/opt/smartdc/pubapi'; application='pubapi'; puts ERB.new(File.read('/opt/smartdc/pubapi/smartdc/unicorn.conf.erb')).result" > /opt/smartdc/pubapi/config/unicorn.conf
  chown jill:jill /opt/smartdc/pubapi/config/unicorn.conf
fi

if [[ ! -e /opt/smartdc/pubapi/tmp/pids ]]; then
  su - jill -c "mkdir -p /opt/smartdc/pubapi/tmp/pids"
fi

echo "Importing Public API Unicorn Manifest"
/usr/sbin/svccfg import /opt/smartdc/pubapi/config/unicorn.smf
sleep 1

# Ensure everything in /opt/smartdc is owned by jill
chown -R jill:jill /opt/smartdc

# fix perms on /home
chown root:root /home
chmod 0555 /home

if [[ ! -e /opt/smartdc/pubapi/db/production.db ]]; then
  echo "Creating Public API database."
  su - jill -c "(cd /opt/smartdc/pubapi; PATH=/opt/local/bin:$PATH RACK_ENV=production /opt/local/bin/rake18 db:migrate)"
fi

# We need to generate our own self signed certificate for Nginx:
echo "Generating SSL Certificate"
/opt/local/bin/openssl req -x509 -nodes -subj '/CN=*' -newkey rsa:4096 -keyout /opt/local/etc/openssl/private/selfsigned.pem -out /opt/local/etc/openssl/private/selfsigned.pem

# Setup and configure nginx
if [[ -z $(/usr/bin/svcs -a|grep nginx) ]]; then
  echo "Importing nginx service"
  cat >/opt/local/etc/nginx/nginx.conf <<NGINX
user www www;
worker_processes 1;
error_log /var/log/nginx/error.log;
#pid /var/spool/nginx/nginx.pid;

events {
    worker_connections 1024;
    use /dev/poll; # important on Solaris
}

http {
    include /opt/local/etc/nginx/mime.types;
    default_type application/octet-stream;
    log_format main '\$remote_addr - \$remote_user [\$time_local] \$request '
                    '"\$status" \$body_bytes_sent "\$http_referer" '
                    '"\$http_user_agent" "\$http_x_forwarded_for"';
    access_log /var/log/nginx/access.log main;
    sendfile off; # important on Solaris
    keepalive_timeout 60;
    server_tokens off;

    upstream pubapi {
        server ${PRIVATE_IP}:8080;
    }

    server {
        listen 443;

        # Self-signed is okay. Production Zeus will handle the real no.de certs.
        ssl on;
        ssl_certificate /opt/local/etc/openssl/private/selfsigned.pem;
        ssl_certificate_key /opt/local/etc/openssl/private/selfsigned.pem;
        ssl_prefer_server_ciphers on;

        location / {
            root /opt/smartdc/pubapi/public;
            proxy_set_header X-Real-IP  \$remote_addr;
            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
            proxy_set_header Host \$http_host;
            proxy_redirect off;

            ## Serve static files
            #if (-f \$request_filename) {
            #    break;
            #}

            proxy_pass http://pubapi;
            break;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root share/examples/nginx/html;
        }
    }
}

NGINX

  /usr/sbin/svccfg import /opt/local/share/smf/manifest/nginx.xml
  /usr/sbin/svcadm enable -s nginx
fi
