#!/usr/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#

if [[ $# != 2 ]]; then
    echo "Usage: $0 <zone_name> <target_directory>"
    exit 1
fi

ROLE=adminui
UUID=$1
TARGET_DIR=$2
CFG_PARENT=/zones/${UUID}/root/opt/smartdc
CFG_DIR=adminui-data
CFG_PATH=${CFG_PARENT}/${CFG_DIR}

if [[ ! -d "${TARGET_DIR}" ]]; then
    echo "Invalid directory: '${TARGET_DIR}'"
    exit 1
fi

# Create the backup directory:
mkdir -p ${TARGET_DIR}/${ROLE}

echo "==> Saving data directory for zone '${ROLE}'"
if [ -d $CFG_PATH ]; then
    (cd ${CFG_PARENT} && tar cbfE 512 - ${CFG_DIR} | \
        gzip >${TARGET_DIR}/${ROLE}/adminui-data.tgz)
fi

echo "==> Done!"
exit 0
