#!/usr/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#

export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
set -o xtrace

PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

role=adminui
app_name=$role

# This includes the fatal function and downloads and installs files.
source /var/svc/setup.common

# Identify this as a smartdc zone
mkdir -p /var/smartdc/adminui
mkdir -p /opt/smartdc/adminui

# Location for ssl cert
mkdir -p /opt/smartdc/adminui/etc/ssl

# We need to generate our own self signed certificate for Nginx:
echo "Generating SSL Certificate"
/opt/local/bin/openssl req -x509 -nodes -subj '/CN=*' \
  -newkey rsa:4096 -days 365 \
    -keyout /opt/smartdc/adminui/etc/ssl/default.pem \
    -out /opt/smartdc/adminui/etc/ssl/default.pem

# Add node_modules/bin to PATH
echo -e "\nexport PATH=\$PATH:/opt/smartdc/adminui/node_modules/.bin:/opt/smartdc/adminui/build/node/bin" >> /root/.bashrc

# do configuration now.
/opt/smartdc/bin/configure || fatal "Unable to configure adminui zone"

touch /var/svc/setup_complete
echo "setup done"
(sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &

exit 0
