#!/bin/bash

echo "99 finalizing adminui zone"

app_name='adminui'

#
# Call symlink_ruby (imported from 97-zoneinit-common)
#
symlink_ruby

#
# Also, from 97-zoneinit-common
#
create_jill_account

# We need to generate our own self signed certificate for Nginx:
echo "Generating SSL Certificate"
/opt/local/bin/openssl req -x509 -nodes -subj '/CN=*' -newkey rsa:4096 -keyout /opt/local/etc/openssl/private/selfsigned.pem -out /opt/local/etc/openssl/private/selfsigned.pem

# Apply configuration from /opt/smartdc/etc/zoneconfig now
source /opt/smartdc/bin/configure.sh

echo "Importing MAPI Admin UI Unicorn Manifest"
/usr/sbin/svccfg import /opt/smartdc/adminui/config/unicorn.smf
sleep 10 # XXX
#/usr/sbin/svccfg -s svc:/network/smartdc/application/adminui:default refresh

# Ensure everything in /opt/smartdc is owned by jill
chown -R jill:jill /opt/smartdc

# fix perms on /home
chown root:root /home
chmod 0555 /home

if [[ ! -n ${KEEP_DATA_DATASET} ]]; then

  ## Call the verify script
  (cd /opt/smartdc/adminui && ./script/verify_setup.sh)

  # Setup for HVM if it's enabled.
  if [[ -n ${HAVE_HVM} && ${HAVE_HVM} == "true" ]]; then
    gsed -i -e "s/^\(development:.*\)/\1\n  hvm_enabled: true/" /opt/smartdc/adminui/config/config.yml
  fi
  cat /opt/smartdc/adminui/config/config.yml

fi

