{
    "build-tgz": "true"
  , "bits-url": "https://stuff.joyent.us/stuff/builds"
  , "bits-url-open": "http://stuff:kie7Ooph@stuff.smartdatacenter.org"
  , "bits-branch": "master"
  , "platform-release": "master"
  , "agents-shar": "master"

  , "adminui-tarball": "adminui/adminui-pkg-master-.*.tar.bz2"
  , "amon-tarball": "amon/amon-pkg-master-.*.tar.bz2"
  , "assets-tarball": "assets/assets-pkg-master-.*.tar.bz2"
  , "ca-tarball": "ca/ca-pkg-master-.*.tar.bz2"
  , "keyapi-tarball": "keyapi/keyapi-pkg-master-.*.tar.bz2"
  , "cloudapi-tarball": "cloudapi/cloudapi-pkg-master-.*.tar.bz2"
  , "cnapi-tarball": "cnapi/cnapi-pkg-master-.*.tar.bz2"
  , "dapi-tarball": "dapi/dapi-pkg-master-.*.tar.bz2"
  , "dcapi-tarball": "dcapi/dcapi-pkg-master-.*.tar.bz2"
  , "dhcpd-tarball": "dhcpd/dhcpd-pkg-master-.*.tar.bz2"
  , "imgapi-tarball": "imgapi/imgapi-pkg-master-.*.tar.bz2"
  , "manatee-tarball": "manatee/manatee-pkg-master-.*.tar.bz2"
  , "moray-tarball": "https://stuff.joyent.us/stuff/builds/moray/streaming-20120904T161630Z/moray/moray-pkg-streaming-20120904T161630Z-g0cfaab6.tar.bz2"
  , "napi-tarball": "napi/napi-pkg-master-.*.tar.bz2"
  , "portal-tarball": "portal/portal-pkg-master-.*.tar.bz2"
  , "rabbitmq-tarball": "rabbitmq/rabbitmq-pkg-master-.*.tar.bz2"
  , "redis-tarball": "redis/redis-pkg-master-.*.tar.bz2"
  , "ufds-tarball": "https://stuff.joyent.us/stuff/builds/ufds/streaming-20120905T080522Z/ufds/ufds-pkg-streaming-20120905T080522Z-ge8313dc.tar.bz2"
  , "usageapi-tarball": "usageapi/usageapi-pkg-master-.*.tar.bz2"
  , "webinfo-tarball": "webinfo/webinfo-pkg-master-.*.tar.bz2"
  , "workflow-tarball": "https://stuff.joyent.us/stuff/builds/workflow/streaming-latest/workflow/workflow-pkg-streaming-20120903T080011Z-g1b78efa.tar.bz2"
  , "vmapi-tarball": "vmapi/vmapi-pkg-master-.*.tar.bz2"
  , "zookeeper-tarball": "none"

  , "datasets": [
      { "name": "smartos-1.6.3"
      , "uuid": "01b2c898-945f-11e1-a523-af1afbe22822"
      , "pkgsrc": "2011Q4"
      , "pkgsrc_url": "http://pkgsrc.joyent.com/sdc/2011Q4/gcc46/All/"
      }
    , { "name": "smartos64-1.6.3"
      , "uuid": "f9e4be48-9466-11e1-bc41-9f993f5dff36"
      , "pkgsrc": "2011Q4_64"
      , "pkgsrc_url": "http://pkgsrc.joyent.com/sdc/2011Q4/gcc46-64/All/"
      }
  ]
}
