{
    "build-tgz": "true"
  , "bits-url": "https://guest:GrojhykMid@stuff.joyent.us/stuff/builds"
  , "bits-branch": "master"
  , "platform-release": "master"
  , "agents-shar": "master"
  , "adminui-tarball": "adminui/adminui-pkg-master-.*.tar.bz2"
  , "amon-tarball": "amon/amon-pkg-master-.*.tar.bz2"
  , "assets-tarball": "assets/assets-pkg-master-.*.tar.bz2"
  , "billapi-tarball": "billapi/billapi-pkg-master-.*.tar.bz2"
  , "ca-tarball": "ca/ca-pkg-master-.*.tar.bz2"
  , "cloudapi-tarball": "cloudapi/cloudapi-pkg-master-.*.tar.bz2"
  , "dhcpd-tarball": "dhcpd/dhcpd-pkg-master-.*.tar.bz2"
  , "mapi-tarball": "mapi/mapi-pkg-master-.*.tar.bz2"
  , "portal-tarball": "portal/portal-pkg-master-.*.tar.bz2"
  , "rabbitmq-tarball": "rabbitmq/rabbitmq-pkg-master-.*.tar.bz2"
  , "redis-tarball": "redis/redis-pkg-master-.*.tar.bz2"
  , "ufds-tarball": "ufds/ufds-pkg-master-.*.tar.bz2"
  , "webinfo-tarball": "webinfo/webinfo-pkg-master-.*.tar.bz2"
  , "workflow-tarball": "workflow/workflow-pkg-master-.*.tar.bz2"
  , "zapi-tarball": "zapi/zapi-pkg-master-.*.tar.bz2"
  , "dapi-tarball": "dapi/dapi-pkg-master-.*.tar.bz2"
  , "cnapi-tarball": "cnapi/cnapi-pkg-master-.*.tar.bz2"
  , "moray-tarball": "moray/moray-pkg-master-.*.tar.bz2"
  , "datasets": [
      { "name": "smartos-1.3.18"
      , "uuid": "47e6af92-daf0-11e0-ac11-473ca1173ab0"
      , "pkgsrc": "2010Q4"
      , "pkgsrc_url": "http://pkgsrc.joyent.com/sdc/2010Q4/gcc45/All/"
      , "headnode_zones": "true"
      }
    , { "name": "smartos64-1.4.7"
      , "uuid": "141194fa-dd77-11e0-8539-27dd8d8264b8"
      , "pkgsrc": "2011Q2_64"
      , "pkgsrc_url": "http://pkgsrc.joyent.com/sdc/2011Q2/gcc45-64/All/"
      }
    , { "name": "smartos-1.6.0"
      , "uuid": "28445220-6eac-11e1-9ce8-5f14ed22e782"
      , "pkgsrc": "2011Q4"
      , "pkgsrc_url": "http://pkgsrc.joyent.com/sdc/2011Q4/gcc46/All/"
      }
    , { "name": "smartos64-1.6.0"
      , "uuid": "76fbfd14-6eb1-11e1-9637-fb5ad39f5bfd"
      , "pkgsrc": "2011Q4_64"
      , "pkgsrc_url": "http://pkgsrc.joyent.com/sdc/2011Q4/gcc46-64/All/"
      }
    , { "name": "ubuntu10.04-0.1.0"
      , "uuid": "56108678-1183-11e1-83c3-ff3185a5b47f"
      }
  ]
}
