#!/usr/bin/bash
# Copyright 2011 Joyent Inc.

. /lib/svc/share/smf_include.sh

ALLOWED_FILE=$(svcprop -p 'capi/allowed_file' ${SMF_FMRI} )
CAPI_PORT=$(svcprop -p 'capi/port' ${SMF_FMRI} )

[[ -f ${ALLOWED_FILE} ]] || exit $SMF_EXIT_OK

> /etc/ipf/ipf.conf

for ip in `cat ${ALLOWED_FILE} | xargs`; do
    echo "pass in quick proto tcp from ${ip} to any port = ${CAPI_PORT} keep state" >> /etc/ipf/ipf.conf
done

echo "block in quick all" >> /etc/ipf/ipf.conf

