#!/usr/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#

if [[ $# != 2 ]]; then
    echo "Usage: $0 <zone_name> <target_directory>"
    exit 1
fi

ZONE=$1
TARGET_DIR=$2
CFG_FILE=/zones/$ZONE/root/opt/smartdc/booter/config.js

if [[ ! -d "${TARGET_DIR}" ]]; then
    echo "Invalid directory: '${TARGET_DIR}'"
    exit 1
fi

# Create the backup directory:
mkdir -p ${TARGET_DIR}/${ZONE}

echo "==> Saving config file for zone '${ZONE}'"
[ -f $CFG_FILE ] && cp $CFG_FILE ${TARGET_DIR}/${ZONE}

echo "==> Done!"
exit 0
