#!/bin/bash
#
# Copyright (c) 2011 Joyent Inc. All rights reserved.
#

set -o xtrace

# This includes the fatal function and downloads and installs files.
source /var/svc/setup.common

echo "Finishing setup of dhcpd zone"

# Apply configuration from /opt/smartdc/etc/zoneconfig now
/opt/smartdc/bin/configure || fatal "Unable to configure zone"

touch /var/svc/setup_complete
echo "setup done"
(sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &

exit 0
