#!/usr/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#

set -o xtrace

PATH=/opt/riak/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# This includes the fatal function and downloads and installs files.
source /var/svc/setup.common

# Load this for RIAK_VERSION AND RIAK_ADMIN_IP*
eval $(cat /opt/smartdc/etc/zoneconfig)

# Cookie to identify this as a SmartDC zone and its role
mkdir -p /var/smartdc/riak
mkdir -p /opt/smartdc/etc

# Install Riak
cd /opt
/usr/bin/gtar -jxf /var/svc/riak.tar.bz2
mkdir -p /var/db/riak /var/log/riak
/usr/sbin/groupadd riak
/usr/sbin/useradd -d /opt/riak -s /usr/bin/bash -g riak riak
/usr/bin/passwd -l riak
/usr/sbin/projadd -c "Riak 1.0 Tunings" -K "process.max-file-descriptor=(basic,65535,deny),(priv,65535,deny)" -U riak -G riak riak
/usr/bin/chown -R riak:riak /opt/riak /var/db/riak /var/log/riak
rm -f /var/svc/riak.tar.bz2

# Start epmd (prereq for riak)
svcadm enable epmd

echo "Generating SSL Certificate"
/opt/local/bin/openssl req -x509 -nodes -subj '/CN=*' -newkey rsa:2048 -keyout /opt/riak/etc/key.pem -out /opt/riak/etc/cert.pem -days 3650

/opt/smartdc/bin/configure || fatal "Unable to complete configuration of riak zone."

# Wait up to 3 minutes for riak svc to be ready
cnt=0
while [ $cnt -lt 18 ]; do
    sleep 10
    riak_state=`svcs -H riak | cut -f1 -d' '`
    [ "$riak_state" == "online" ] && break
    cnt=$(($cnt + 1))
done
[ $cnt == 18 ] && \
    echo "WARNING: riak svc still not online after 3 minutes"

# If not the first riak zone, then join the existing cluster.
join_riak_ips=`set | nawk -F= -v myaddr=$IPADDR \
    '/^RIAK_ADMIN_IP/ {if ($2 != myaddr) print $2}'`
for i in $join_riak_ips
do
	# HOME must be set for 'erlexec' (used in riak-admin)
	export HOME=/root
	echo "join riak cluster at $i"
	riak-admin join riak@$i
	[ $? == 0 ] && break
done

touch /var/svc/setup_complete
echo "setup done"
(sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &

exit 0
