#!/usr/bin/bash

# This script runs with the $CONFIG_assets_ip variable set to the assets zone
# IP address.  Its up to this script to pull down the rest of the files it
# needs from the assets zone and setup the zone for the given role.  This
# script is run in the background by the mdata svc so its ok if it takes
# a little while to install all of the pkgs.

PATH=/opt/riak/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

role=riak

cd /var/svc

curl -k -o zoneconfig -s $CONFIG_assets_ip:/extra/$role/zoneconfig
curl -k -o hn_config -s $CONFIG_assets_ip:/extra/$role/hn_config
curl -k -o hn_generic -s $CONFIG_assets_ip:/extra/$role/hn_generic

# We need some of the headnode IP addrs, but don't leave the file around
. /var/svc/hn_config
. /var/svc/hn_generic
rm -f /var/svc/hn_config
# Load up the config values
. /var/svc/zoneconfig

# The user-script is downloaded and executed on every zone boot. We take
# advantage of this to maintain the cached config values post-setup.
if [ -e /var/svc/setup_complete ]; then
	echo RIAK_COOKIE=$RIAK_COOKIE >/opt/smartdc/etc/zoneconfig
	exit 0
fi

# Setup the zone
curl -o pkgsrc -s $CONFIG_assets_ip:/extra/$role/pkgsrc_2011q2_64
curl -o fs.tar.bz2 -s $CONFIG_assets_ip:/extra/$role/fs.tar.bz2
curl -o pkgsrc.tar -s $CONFIG_assets_ip:/extra/pkgsrc/pkgsrc_2011q2_64.tar
curl -o riak-1.0.0.tar.bz2 -s $CONFIG_assets_ip:/extra/$role/riak-1.0.0.tar.bz2

# Cookie to identify this as a SmartDC zone and its role
mkdir -p /var/smartdc/riak

# Unpack fs.tar and copy files into proper locations within the zone
mkdir /.stage
echo "unpack fs.tar"
(cd /.stage; bzcat /var/svc/fs.tar.bz2 | tar xbf 512 -)
rm -f /var/svc/fs.tar.bz2
echo "install root"
(cd /.stage/root; tar cbf 512 - *) | (cd /; tar xbf 512 -)
rm -rf /.stage

# Install using local pkg repo
mkdir -p /var/svc/pkgs
(cd /var/svc/pkgs && tar -xf /var/svc/pkgsrc.tar \
      $(cat /var/svc/pkgsrc | sed -e "s/$/.tgz/" | xargs))
rm -f /var/svc/pkgsrc.tar

for i in `cat /var/svc/pkgsrc`
do
	echo "Installing $i"
	pkg_info $i >/dev/null 2>&1 || pkg_add -f /var/svc/pkgs/$i
done
rm -rf /var/svc/pkgs

mkdir -p /opt/smartdc/etc
echo RIAK_COOKIE=$RIAK_COOKIE >/opt/smartdc/etc/zoneconfig

# Install Riak
cd /opt
/usr/bin/gtar -jxf /var/svc/riak-1.0.0.tar.bz2
mkdir -p /var/db/riak /var/log/riak

/usr/sbin/groupadd riak
/usr/sbin/useradd -d /opt/riak -s /usr/bin/bash -g riak riak
/usr/bin/passwd -l riak
/usr/sbin/projadd -c "Riak 1.0 Tunings" -K "process.max-file-descriptor=(basic,65535,deny),(priv,65535,deny)" -U riak -G riak riak
/usr/bin/chown -R riak:riak /opt/riak /var/db/riak /var/log/riak

rm -f /var/svc/riak-1.0.0.tar.bz2

# Update RIAK node name and cluster cookie
IPADDR=`/usr/sbin/ifconfig net0 | /usr/bin/nawk '/inet/ {print $2}'`
gsed -i -e s/127.0.0.1/$IPADDR/ /opt/riak/etc/app.config

gsed -i -e "s/riak@127.0.0.1/riak@$IPADDR/" /opt/riak/etc/vm.args
gsed -i -e "s/setcookie riak/setcookie $RIAK_COOKIE/" /opt/riak/etc/vm.args


svccfg import /site/riak_smf_manifest.xml
svcadm enable riak
sleep 5

svcs riak

# If not the first riak zone, then join the cluster.
if [ -n "$riak_admin_ip" ]; then
	echo "join riak cluster at $riak_admin_ip"
	riak-admin join riak@$riak_admin_ip
fi

touch /var/svc/setup_complete
echo "setup done"
(sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &
