#!/bin/bash

echo "99 finalizing riak zone"

echo "Configuring RIAK:"
echo "Binding RIAK to Admin IP."
$(/opt/local/bin/gsed -i"" -e "s/127.0.0.1/${PRIVATE_IP}/" /opt/local/etc/riak/app.config)
echo "Updating RIAK node name."
$(/opt/local/bin/gsed -i"" -e "s/riak@127.0.0.1/riak@${PRIVATE_IP}/" /opt/local/etc/riak/vm.args)
echo "Setting RIAK cluster cookie"
$(/opt/local/bin/gsed -i"" -e "s/setcookie riak/setcookie ${RIAK_COOKIE}/" /opt/local/etc/riak/vm.args)


# Apply configuration from /opt/smartdc/etc/zoneconfig now
source /opt/smartdc/bin/configure.sh

# Ensure that we get the correct /etc/project settings for riak and FD limits
gsed -i '/^riak/ c\riak:100:Riak default project:riak:riak:process.max-file-descriptor=(basic,65535,deny),(priv,65535,deny)' /etc/project

# Update maximum ports so Riak doesn't (easily) run out of them during operation
gsed -i'' -e 's/ERL_MAX_PORTS [0-9][0-9]*/ERL_MAX_PORTS 65536/' /opt/local/etc/riak/vm.args

echo "Importing RIAK manifest"
/usr/sbin/svccfg import /opt/local/share/smf/manifest/epmd.xml
/usr/sbin/svcadm enable -s epmd
sleep 2
/usr/sbin/svccfg import /opt/local/share/smf/manifest/riak.xml
/usr/sbin/svcadm enable riak

