#!/bin/bash

echo "99 finalizing riak zone"

echo "Configuring RIAK:"
echo "Binding RIAK to Admin IP."
$(/opt/local/bin/gsed -i"" -e "s/127.0.0.1/${PRIVATE_IP}/" /opt/local/etc/riak/app.config)
echo "Updating RIAK node name."
$(/opt/local/bin/gsed -i"" -e "s/riak@127.0.0.1/riak@${PRIVATE_IP}/" /opt/local/etc/riak/vm.args)
echo "Setting RIAK cluster cookie"
$(/opt/local/bin/gsed -i"" -e "s/setcookie riak/setcookie ${RIAK_COOKIE}/" /opt/local/etc/riak/vm.args)


# Apply configuration from /opt/smartdc/etc/zoneconfig now
source /opt/smartdc/bin/configure.sh

echo "Importing RIAK manifest"
/usr/sbin/svccfg import /opt/local/share/smf/manifest/epmd.xml
/usr/sbin/svcadm enable -s epmd
sleep 2
/usr/sbin/svccfg import /opt/local/share/smf/manifest/riak.xml
/usr/sbin/svcadm enable riak


