#!/bin/bash

set -o xtrace

PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Only want to run this initial user-script once
if [[ -f /var/svc/.ran-user-script ]]; then
    echo "Initial user-script has already been run."
    exit 0
fi
touch /var/svc/.ran-user-script

zone_uuid=$(zonename)
zone_role=$(mdata-get sdc:tags.smartdc_role)
if [[ -z ${zone_role} ]]; then
    echo "Unable to find zone role in metadata."
    exit 1
fi

pkgsrc_lst=$(ls -1 /assets/extra/${zone_role}/pkgsrc_*)
pkgsrc_tar=/assets/extra/pkgsrc/$(basename ${pkgsrc_lst}).tar

# Install using local pkg repo
mkdir -p /var/svc/pkgs
(cd /var/svc/pkgs && tar -xf ${pkgsrc_tar} \
      $(cat ${pkgsrc_lst} | sed -e "s/$/.tgz/" | xargs))

for i in $(cat ${pkgsrc_lst})
do
        echo "Installing $i"
        pkg_info $i >/dev/null 2>&1 || pkg_add -f /var/svc/pkgs/$i
done
rm -rf /var/svc/pkgs

mkdir -p /opt/smartdc/bin
for file in configure configure.sh backup restore setup; do
    if [[ -f /assets/extra/${zone_role}/${file} ]]; then
        cp /assets/extra/${zone_role}/${file} /opt/smartdc/bin/${file}
    fi
done
chmod 755 /opt/smartdc/bin/*

if [[ -f /opt/smartdc/bin/setup ]]; then
    bash /opt/smartdc/bin/setup >/var/svc/setup.log 2>&1 &
fi

exit 0
