#!/bin/bash

set -o xtrace

PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

fatal() {
    echo $* >&2
    exit 1
}

zone_uuid=$(zonename)
zone_role=$(mdata-get sdc:tags.smartdc_role)
if [[ -z ${zone_role} ]]; then
    echo "Unable to find zone role in metadata."
    exit 1
fi

if [[ ! -d /opt/smartdc/etc ]]; then
    mkdir -p /opt/smartdc/etc
fi
if [[ -f /assets/extra/${zone_role}/zoneconfig ]]; then
    cp /assets/extra/${zone_role}/zoneconfig /opt/smartdc/etc/zoneconfig || \
        fatal "unable to copy zoneconfig file"
fi
touch /opt/smartdc/etc/zoneconfig

mkdir -p /opt/smartdc/bin
for file in configure backup restore setup; do
    if [[ -f /assets/extra/${zone_role}/${file} ]]; then
        cp /assets/extra/${zone_role}/${file} /opt/smartdc/bin/${file}
    fi
done
chmod 755 /opt/smartdc/bin/*

# Run the configure whenever we didn't do setup already
if [[ -f /var/svc/setup_complete ]]; then
    # We already did setup (which ran configure last time), so just reconfigure
    /opt/smartdc/bin/configure
fi

# Only want to run this initial user-script once
if [[ -f /var/svc/.ran-user-script ]]; then
    echo "Initial user-script has already been run."
    exit 0
fi
touch /var/svc/.ran-user-script



pkgsrc_version=$(cat /opt/local/etc/pkgin/repositories.conf | cut -d '/' -f5 | tr [:lower:] [:upper:])
[[ $? != 0 ]] && fatal "FATAL: unable to get pkgsrc version"
if [[ -n $(cat /opt/local/etc/pkgin/repositories.conf | cut -d '/' -f6 | grep "\-64$") ]]; then
    pkgsrc_version=${pkgsrc_version}_64
fi
pkgsrc_lst=/assets/extra/${zone_role}/pkgsrc
pkgsrc_dir=/assets/extra/pkgsrc/${pkgsrc_version}

# Install using local pkg repo
for i in $(cat ${pkgsrc_lst})
do
        echo "Installing $i"
        pkg_info $i >/dev/null 2>&1 || pkg_add -f ${pkgsrc_dir}/$i
done

bash /opt/smartdc/bin/setup >/var/svc/setup.log 2>&1 &
if [[ $? != 0 ]]; then
    echo "Failed to setup zone"
    exit 1
fi

exit 0
