#!/usr/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#

set -o xtrace

PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

role=clortho
app_name=$role

# This includes the fatal function and downloads and installs files.
source /var/svc/setup.common

# Cookie to identify this as a SmartDC zone and its role
mkdir -p /var/smartdc/clortho

# Install CLORTHO
mkdir -p /opt/smartdc/clortho
chown -R nobody:nobody /opt/smartdc/clortho

# Add build/node/bin and node_modules/.bin to PATH
echo "" >>/root/.bashrc
echo "export PATH=\$PATH:/opt/smartdc/clortho/build/node/bin:/opt/smartdc/clortho/node_modules/.bin" >>/root/.bashrc


/opt/smartdc/bin/configure || fatal "Unable to configure zone."


touch /var/svc/setup_complete
echo "setup done"
(sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &

exit 0
