#!/usr/bin/bash

set -o errexit
set -o pipefail
set -o xtrace

TIMESTAMP=$1
CONFIGS=/opt/smartdc/node.config
TEMP_CONFIGS=/var/tmp/node.config
JOYSETUP=/opt/smartdc/joysetup/joysetup.sh

if [[ -z $TIMESTAMP ]]; then
  echo "cannot create joysetupper script without a timestamp"
  exit 1
fi

if [[ ! -d $CONFIGS ]]; then
  echo "configs directory doesn't exist"
  exit 1
fi

if [[ ! -f $JOYSETUP ]]; then
  echo "joysetup.sh doesn't exist"
  exit 1
fi

FILENAME=/opt/smartdc/joysetup/joysetupper-${TIMESTAMP}.sh
TMP=/var/tmp

cp -R $CONFIGS /var/tmp/

# Run the script from /var/tmp in case we need to write to some log later
(cat <<__EOF__
#!/bin/bash
P=\$(cd \`dirname \$0\` && pwd)
if [ \`pwd\` != '$TMP' ]; then
  cd $TMP
  /bin/bash \$P/\`basename \$0\`
  exit
fi
__EOF__
)> $FILENAME

(/opt/local/bin/shar -n "Joyent" $TEMP_CONFIGS | grep -v '^exit 0')>> $FILENAME

(cat $JOYSETUP)>> $FILENAME

rm -rf $TEMP_CONFIGS

echo "Done."
