#!/usr/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#

export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
set -o xtrace

PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

role=sdcsso
app_name=$role

echo "Generating SSL Certificate"
mkdir -p /opt/smartdc/$role/ssl/
/opt/local/bin/openssl req -x509 -nodes -subj '/CN=*' -newkey rsa:2048 \
    -keyout /opt/smartdc/$role/ssl/key.pem \
    -out /opt/smartdc/$role/ssl/cert.pem -days 365

# This includes the fatal function and downloads and installs files.
source /var/svc/setup.common

# Cookie to identify this as a SmartDC zone and its role
mkdir -p /var/smartdc/sdcsso

# Install KeyAPI
mkdir -p /opt/smartdc/sdcsso
chown -R nobody:nobody /opt/smartdc/sdcsso

# Add build/node/bin and node_modules/.bin to PATH
echo "" >>/root/.bashrc
echo "export PATH=\$PATH:/opt/smartdc/sdcsso/build/node/bin:/opt/smartdc/sdcsso/node_modules/.bin" >>/root/.bashrc


/opt/smartdc/bin/configure || fatal "Unable to configure zone."


touch /var/svc/setup_complete
echo "setup done"
(sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &

exit 0
