#!/usr/bin/bash

unset LD_LIBRARY_PATH
PATH=/usr/bin:/usr/sbin
export PATH

if [[ $# != 2 ]]; then
  echo "Usage: $0 <zone_name> <target_directory>"
  exit 1
fi

ZONE=$1
TARGET_DIR=$2
ROLE="redis"

if [[ ! -d "${TARGET_DIR}" || ! -d ${TARGET_DIR}/${ROLE} ]]; then
    echo "Missing backup directory"
    exit 107
fi

if [[ ! -f ${TARGET_DIR}/${ROLE}/etc.tar ]]; then
    echo "Incomplete backup directory"
    exit 109
fi

if [[ ! -f ${TARGET_DIR}/${ROLE}/var_db.tar ]]; then
    echo "Incomplete backup directory"
    exit 110
fi

echo "==> Restoring $ROLE backup"
(cd /zones/$ZONE/root/var/db; tar xbf 512 ${TARGET_DIR}/${ROLE}/var_db.tar)
if [[ $? -ne 0 ]]; then
    echo "Error: restoring database"
    exit 111
fi
(cd /zones/$ZONE/root/opt/redis/etc; \
    tar xbf 512 ${TARGET_DIR}/${ROLE}/etc.tar)
if [[ $? -ne 0 ]]; then
    echo "Error: restoring configuration"
    exit 112
fi

echo "All done!!!"
exit 0
