#!/usr/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#

set -o xtrace

PATH=/opt/redis/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# This includes the fatal function and downloads and installs files.
source /var/svc/setup.common

# Cookie to identify this as a SmartDC zone and its role
mkdir -p /var/smartdc/redis

# Install Redis
cd /opt
/usr/bin/gtar -jxf /var/svc/redis-2.4.1.tar.bz2
mkdir -p /var/db/redis /var/log/redis
/usr/sbin/groupadd redis
/usr/sbin/useradd -d /opt/redis -s /usr/bin/bash -g redis redis
/usr/bin/passwd -l redis
/usr/sbin/projadd -c "Redis Tunings" -K "process.max-file-descriptor=(basic,65535,deny),(priv,65535,deny)" -U redis -G redis redis
/usr/bin/chown -R redis:redis /opt/redis /var/db/redis /var/log/redis
rm -f /var/svc/redis-2.4.1.tar.bz2

/opt/smartdc/bin/configure || fatal "Unable to configure zone."

touch /var/svc/setup_complete
echo "setup done"
(sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &

exit 0
