#!/usr/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#

set -o xtrace

PATH=/opt/nodejs/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# This includes the fatal function and downloads and installs files.
source /var/svc/setup.common

eval $(cat /opt/smartdc/etc/zoneconfig)

# Install UFDS
mkdir -p /opt/smartdc/ufds/ssl
chown -R nobody:nobody /opt/smartdc/ufds

# Install node/npm
echo "Installing node and npm"
cd /opt
/usr/bin/gtar -j -m -xf /var/svc/nodejs-0.4.12.tar.bz2
/usr/bin/chown -R nobody:nobody /opt/nodejs /opt/smartdc
rm -f /var/svc/nodejs-0.4.12.tar.bz2

echo "Creating log directory"
mkdir -p /var/log/ufds
chown -R nobody:nobody /var/log/ufds

echo "Generating SSL Certificate"
/opt/local/bin/openssl req -x509 -nodes -subj '/CN=*' -newkey rsa:2048 -keyout /opt/smartdc/ufds/ssl/key.pem -out /opt/smartdc/ufds/ssl/cert.pem -days 365

/opt/smartdc/bin/configure || fatal "Unable to configure zone."

sleep 5
echo "Loading bootstrap data"
cat > /tmp/.bootstrap.ldif <<HERE
version: 1

dn: o=smartdc
objectclass: organization
o: smartdc

dn: ou=users, o=smartdc
objectclass: organizationalUnit
ou: users

dn: ou=groups, o=smartdc
objectclass: organizationalUnit
ou: groups

dn: uuid=${UFDS_ADMIN_UUID}, ou=users, o=smartdc
login: ${UFDS_ADMIN_LOGIN}
uuid: ${UFDS_ADMIN_UUID}
userpassword: ${UFDS_ADMIN_PW}
email: ${UFDS_ADMIN_EMAIL}
cn: Admin
sn: User
objectclass: sdcPerson

dn: cn=operators, ou=groups, o=smartdc
uniquemember: uuid=${UFDS_ADMIN_UUID}, ou=users, o=smartdc
objectclass: groupOfUniqueNames

HERE

LDAPTLS_REQCERT=allow /opt/local/bin/ldapadd -H ldaps://127.0.0.1:636 -x -D ${UFDS_LDAP_ROOT_DN} -w ${UFDS_LDAP_ROOT_PW} -f /tmp/.bootstrap.ldif
if [ $? -ne 0 ] ; then
    echo "Failed to load bootstrap data, exiting"
    echo "Marking ufds SMF service as in maintenance"
    svcadm mark maintenance svc:/smartdc/site/ufds:default
    exit 1
fi

rm -f /tmp/.bootstrap.ldif

touch /var/svc/setup_complete
echo "setup done"
(sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &

exit 0
