#!/usr/bin/bash
#
# Copyright (c) 2013 Joyent Inc., All rights reserved.
#

export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
set -o xtrace

PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

role=manta
app_name=$role

# This includes the fatal function and downloads and installs files.
source /var/svc/setup.common

# Cookie to identify this as a SmartDC zone and its role
mkdir -p /var/smartdc/manta-deployment

# Install deployment tools
mkdir -p /opt/smartdc/manta-deployment
chown -R nobody:nobody /opt/smartdc/manta-deployment

# Add build/node/bin and node_modules/.bin to PATH
echo "" >>/root/.profile
echo "export PATH=\$PATH:/opt/smartdc/manta-deployment/build/node/bin:/opt/smartdc/manta-deployment/bin:/opt/smartdc/sapi/node_modules/.bin" >>/root/.profile


/opt/smartdc/bin/configure || fatal "Unable to configure zone."

# Enable Cron
echo "Starting Cron"
svccfg import /lib/svc/manifest/system/cron.xml
svcadm enable cron

echo '0 * * * * /usr/sbin/logadm' > /etc/cron.d/logadm
crontab /etc/cron.d/logadm

touch /var/svc/setup_complete
echo "setup done"
(sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &

exit 0
