#!/usr/bin/bash
#
# Copyright (c) 2012 Joyent Inc., All rights reserved.
#

set -o xtrace

PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

role=workflow
app_name=$role

# This includes the fatal function and downloads and installs files.
source /var/svc/setup.common

# Cookie to identify this as a SmartDC zone and its role
mkdir -p /var/smartdc/workflow
mkdir -p /opt/smartdc/workflow/ssl

mkdir -p /opt/smartdc/workflow/etc
/usr/bin/chown -R root:root /opt/smartdc

# Setup HAProxy user/group
/usr/sbin/groupadd haproxy
/usr/sbin/useradd -d /tmp -g haproxy -s /usr/bin/false haproxy
/usr/bin/passwd -N haproxy

echo "Generating SSL Certificate"
/opt/local/bin/openssl req -x509 -nodes -subj '/CN=*' -newkey rsa:2048 -keyout /opt/smartdc/workflow/ssl/key.pem -out /opt/smartdc/workflow/ssl/cert.pem -days 365

# Add build/node/bin and node_modules/.bin to PATH
echo "" >>/root/.bashrc
echo "export PATH=\$PATH:/opt/smartdc/workflow/build/node/bin:/opt/smartdc/workflow/node_modules/.bin" >>/root/.bashrc

/opt/smartdc/bin/configure || fatal "Failed to configure zone."

touch /var/svc/setup_complete
echo "setup done"
(sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &

exit 0

