#!/usr/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#

export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
set -o xtrace

PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

role=keyapi
app_name=$role

# SAPI manifests
CONFIG_AGENT_LOCAL_MANIFESTS_DIRS=/opt/smartdc/keyapi

# This includes the fatal function and downloads and installs files.
source /var/svc/setup.common

# Cookie to identify this as a SmartDC zone and its role
mkdir -p /var/smartdc/keyapi

# Install KeyAPI
mkdir -p /opt/smartdc/keyapi
chown -R nobody:nobody /opt/smartdc/keyapi

# Add build/node/bin and node_modules/.bin to PATH
echo "" >>/root/.profile
echo "export PATH=\$PATH:/opt/smartdc/keyapi/build/node/bin:/opt/smartdc/keyapi/node_modules/.bin" >>/root/.profile


/opt/smartdc/bin/configure || fatal "Unable to configure zone."


touch /var/svc/setup_complete
echo "setup done"
(sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &

exit 0
