#!/bin/bash

echo "99 finalizing cloudauth zone"

echo "Generating SSL Certificate"
/opt/local/bin/openssl req -x509 -nodes -subj '/CN=*' -newkey rsa:2048 -keyout /opt/smartdc/cloudauth/ssl/key.pem -out /opt/smartdc/cloudauth/ssl/cert.pem -days 365

echo "Creating SMF manifest"
cat > /opt/smartdc/cloudauth/cloudauth_manifest.xml <<HERE
<?xml version="1.0"?>
<!DOCTYPE service_bundle SYSTEM "/usr/share/lib/xml/dtd/service_bundle.dtd.1">
<service_bundle type="manifest" name="cloudauth">
  <service name="smartdc/site/cloudauth" type="service" version="0.0.1">

    <create_default_instance enabled="true"/>
    <single_instance/>

    <dependency name="network" grouping="require_all" restart_on="error" type="service">
      <service_fmri value="svc:/milestone/network:default"/>
    </dependency>

    <dependency name="filesystem" grouping="require_all" restart_on="error" type="service">
      <service_fmri value="svc:/system/filesystem/local"/>
    </dependency>

    <exec_method
      type="method"
      name="start"
      exec="/opt/local/bin/node server.js &amp;"
      timeout_seconds="60">
      <method_context working_directory="/opt/smartdc/cloudauth">
        <method_credential user="nobody" group="nobody" privileges="basic,net_privaddr"/>
        <method_environment>
          <envvar name="PATH" value="/usr/local/bin:/opt/local/bin:/usr/bin:/usr/sbin:/bin"/>
          <envvar name="PORT" value="443" />
          <envvar name="NODE_ENV" value="production" />
        </method_environment>
      </method_context>
    </exec_method>

    <exec_method type="method" name="restart" exec=":kill" timeout_seconds="60">
      <method_context working_directory="/opt/smartdc/cloudauth">
        <!-- <method_credential user="root" group="staff"/> -->
      </method_context>
    </exec_method>

    <exec_method type="method" name="stop" exec=":kill" timeout_seconds="60">
      <method_context working_directory="/opt/smartdc/cloudauth">
        <!-- <method_credential user="root" group="staff"/> -->
      </method_context>
    </exec_method>

    <property_group name="startd" type="framework">
      <propval name="ignore_error" type="astring" value="core,signal"/>
    </property_group>

    <property_group name="application" type="application">

    </property_group>


    <stability value="Evolving"/>

    <template>
      <common_name>
        <loctext xml:lang="C">Cloudauth daemon (node)</loctext>
      </common_name>
    </template>

  </service>

</service_bundle>
HERE

# Apply configuration from /opt/smartdc/etc/zoneconfig now
source /opt/smartdc/bin/configure.sh

echo Importing cloudauth_manifest.xml
/usr/sbin/svccfg import /opt/smartdc/cloudauth/cloudauth_manifest.xml

sleep 10 # XXX
echo Enablig service cloudauth
/usr/sbin/svcadm enable smartdc/site/cloudauth
