#!/usr/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#

if [[ $# != 2 ]]; then
    echo "Usage: $0 <zone_name> <src_directory>"
    exit 1
fi

ZONE=$1
SRC_DIR=$2
CFG_FILE=/zones/$ZONE/root/opt/smartdc/portal/cfg/capi.json

# Older backups may not have had this zone
if [[ -d "${SRC_DIR}/${ZONE}" && -f "${SRC_DIR}/${ZONE}/capi.json" ]]; then
	echo "==> Restoring config file for zone '${ZONE}'"
	cp ${SRC_DIR}/${ZONE}/capi.json $CFG_FILE

else
	echo "Warning, older backup; missing config file for $ZONE"
fi

echo "==> Done"
exit 0
