#!/usr/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#

if [[ $# != 2 ]]; then
    echo "Usage: $0 <zone_name> <src_directory>"
    exit 1
fi

ZONE=$1
SRC_DIR=$2
ROLE="portal"

ZONEPATH=`zonecfg -z $ZONE info zonepath | cut -d " " -f2`

BASE_DIR=$ZONEPATH/root/opt/smartdc/portal

# Older backups may not have backed up this role
if [[ -d "${SRC_DIR}/${ROLE}" && -f "${SRC_DIR}/${ROLE}/config.tar" ]]; then
    echo "==> Restoring config files for zone '${ZONE}'"

    cd $BASE_DIR
    tar xbf 512 ${SRC_DIR}/${ROLE}/config.tar

    # run our 6.5.* upgrader!
    echo "==> Upgrading configuration for $ROLE"

    cd $BASE_DIR/tools
    /opt/local/bin/node upgrade_config.js

else
    echo "Warning, older backup; missing config files for $ROLE"
fi


echo "==> Done"
exit 0
