#!/bin/bash

echo "99 finalizing portal zone"

# We need to generate our own self signed certificate for Nginx:
echo "Generating SSL Certificate"
/opt/local/bin/openssl req -x509 -nodes -subj '/CN=*' -newkey rsa:4096 -keyout /opt/local/etc/openssl/private/selfsigned.pem -out /opt/local/etc/openssl/private/selfsigned.pem

echo Creating manifest for portal: 
cat > /opt/smartdc/portal/portal_manifest.xml <<HERE
<?xml version="1.0"?>
<!DOCTYPE service_bundle SYSTEM "/usr/share/lib/xml/dtd/service_bundle.dtd.1">
<service_bundle type="manifest" name="portal">
  <service name="smartdc/site/portal" type="service" version="0.0.1">

    <create_default_instance enabled="true"/>
    <single_instance/>

    <dependency name="network" grouping="require_all" restart_on="error" type="service">
      <service_fmri value="svc:/milestone/network:default"/>
    </dependency>

    <dependency name="filesystem" grouping="require_all" restart_on="error" type="service">
      <service_fmri value="svc:/system/filesystem/local"/>
    </dependency>

    <exec_method
      type="method"
      name="start"
      exec="/opt/local/bin/node server.js &amp;"
      timeout_seconds="60">
      <method_context working_directory="/opt/smartdc/portal">
        <method_credential user="nobody" group="nobody" privileges="basic,net_privaddr"/>
        <method_environment>
          <envvar name="PATH" value="/usr/local/bin:/opt/local/bin:/usr/bin:/usr/sbin:/bin"/>
          <envvar name="NODE_PATH" value="/opt/smartdc/portal/deps"/>
          <envvar name="PORT" value="4000" />
          <envvar name="NODE_ENV" value="production" />
        </method_environment>
      </method_context>
    </exec_method>

    <exec_method type="method" name="restart" exec=":kill" timeout_seconds="60">
      <method_context working_directory="/opt/smartdc/portal">
        <!-- <method_credential user="root" group="staff"/> -->
      </method_context>
    </exec_method>

    <exec_method type="method" name="stop" exec=":kill" timeout_seconds="60">
      <method_context working_directory="/opt/smartdc/portal">
        <!-- <method_credential user="root" group="staff"/> -->
      </method_context>
    </exec_method>

    <property_group name="startd" type="framework">
      <propval name="ignore_error" type="astring" value="core,signal"/>
    </property_group>

    <property_group name="application" type="application">

    </property_group>


    <stability value="Evolving"/>

    <template>
      <common_name>
        <loctext xml:lang="C">Portal daemon (node)</loctext>
      </common_name>
    </template>

  </service>

</service_bundle>
HERE

# Save the zoneconfig file on the configure dir (for testing purposes right now)
mkdir -p /opt/smartdc/etc
cat /root/zoneconfig > /opt/smartdc/etc/zoneconfig
# Source the configure.sh script now:
source /opt/smartdc/bin/configure.sh

echo Importing portal_manifest.xml
svccfg import /opt/smartdc/portal/portal_manifest.xml
echo Enablig service portal
svcadm enable smartdc/site/portal

