#!/bin/bash

POSTGRES=10.99.99.8
PGPASSWORD=postgres

svcadm clear network/physical:default >/dev/null 2>&1

echo "99 finalizing capi zone"

app_name='capi'

echo "Creating $app_name-update service"

cat >"/opt/local/share/smf/manifest/$app_name-update.xml" <<SMF
<?xml version='1.0'?>
<!DOCTYPE service_bundle SYSTEM '/usr/share/lib/xml/dtd/service_bundle.dtd.1'>
<service_bundle type='manifest' name='export'>
  <service name='platform/smartdc/${app_name}-update' type='service' version='0'>
    <create_default_instance enabled='true'/>
    <single_instance/>
    <dependency name='filesystem' grouping='require_all' restart_on='error' type='service'>
      <service_fmri value='svc:/system/filesystem/local'/>
    </dependency>
    <exec_method name='start' type='method' exec='/opt/smartdc/$app_name-data/$app_name-update-service.sh' timeout_seconds='60'>
      <method_context>
        <method_credential user='root' group='root'/>
      </method_context>
    </exec_method>
    <exec_method name='stop' type='method' exec=':true' timeout_seconds='0'/>
    <property_group name='application' type='application'/>
    <property_group name='startd' type='framework'>
      <propval name='duration' type='astring' value='transient'/>
    </property_group>
    <stability value='Evolving'/>
    <template>
      <common_name>
        <loctext xml:lang='C'>SmartDC Update service ($app_name)</loctext>
      </common_name>
    </template>
  </service>
</service_bundle>
SMF

if [[ ! $(/usr/bin/svcs -a|grep ${app_name}-update) ]]; then
  echo "Importing '${app_name}-update' service"
  $(/usr/sbin/svccfg import /opt/local/share/smf/manifest/$app_name-update.xml)
fi

if [[  "$(/usr/bin/svcs -Ho state ${app_name}-update)" != "online"  ]]; then
  echo "Enabling '${app_name}-update' service"
  $(/usr/sbin/svcadm enable -s ${app_name}-update)
fi

# Configure nsswitch to use mdns & enable multicast dns:
hosts=$(cat /etc/nsswitch.conf |grep ^hosts)

if [[ ! $(echo $hosts | grep mdns) ]]; then
  echo "Updating hosts entry on nsswitch.conf"
  $(/opt/local/bin/gsed -i"" -e "s/^hosts.*$/hosts: files mdns dns/" /etc/nsswitch.conf)
fi

ipnodes=$(cat /etc/nsswitch.conf |grep ^ipnodes)

if [[ ! $(echo $ipnodes | grep mdns) ]]; then
  echo "Updating ipnodes entry on nsswitch.conf"
  $(/opt/local/bin/gsed -i"" -e "s/^ipnodes.*$/ipnodes: files mdns dns/" /etc/nsswitch.conf)
fi

# XXX - Is this needed for the CAPI zone?
# Do not use dns/multicast for this zone, we're using custom mDNSResponder from
# pkgsrc here:
#if [[ "$(/usr/bin/svcs -Ho state dns/multicast)" == "online" ]]; then
#  echo "Disabling dns/multicast"
#  $(/usr/sbin/svcadm disable dns/multicast)
#fi
#
#if [[ ! $(/usr/bin/svcs -a|grep mdnsresponder) ]]; then
#  echo "Importing mDNSResponder service"
#  $(/usr/sbin/svccfg import /opt/local/share/smf/manifest/mdnsresponder.xml)
#fi
#
#if [[  "$(/usr/bin/svcs -Ho state mdnsresponder)" != "online"  ]]; then
#  echo "Enabling mDNSResponder service."
#  $(/usr/sbin/svcadm enable -s mdnsresponder)
#fi

# These happen to do not be created always:
if [[ ! -e /opt/local/bin/ruby ]]; then
  echo "Symlinking ruby"
  ln -s /opt/local/bin/ruby18 /opt/local/bin/ruby
fi

if [[ ! -e /opt/local/bin/irb ]]; then
  echo "Symlinking irb"
  ln -s /opt/local/bin/irb18 /opt/local/bin/irb
fi

echo "Creating jill account"
groupadd jill
useradd -g jill -d /opt/smartdc jill
chown -R jill:jill /opt/smartdc
echo "jill:naiWaic8sh" | /root/changepass -n -m > /dev/null 2>&1
usermod -P 'Service Management' jill
usermod -s /usr/bin/bash jill

if [[ -z $(psql -U postgres -h $POSTGRES -c "\\l"|grep capi) ]]; then
  echo "Creating capi database"
  echo "$POSTGRES:*:*:postgres:$PGPASSWORD" >> /opt/smartdc/.pgpass
  chown jill /opt/smartdc/.pgpass
  chmod 0600 /opt/smartdc/.pgpass
  psql -U postgres -h $POSTGRES -c 'CREATE DATABASE capi WITH OWNER postgres'
fi

if [[ ! -e /opt/smartdc/capi/config/database.yml ]]; then
  echo "Creating Customers API config files."
  su - jill -c "cd /opt/smartdc/capi; /opt/local/bin/rake dev:configs -f /opt/smartdc/capi/Rakefile"
fi
sleep 1

# Note these files should have been created by previous Rake task.
# If we copy these files post "gsed", everything is reset:
if [[ ! -e /opt/smartdc/capi/config/config.ru ]]; then
  cp /opt/smartdc/capi/config/config.ru.sample /opt/smartdc/capi/config/config.ru
fi

if [[ ! -e /opt/smartdc/capi/config/config.yml ]]; then
  cp /opt/smartdc/capi/config/config.yml.sample /opt/smartdc/capi/config/config.yml
fi

if [[ $(ls /opt/smartdc/capi/gems/gems| wc -l) -eq 0 ]]; then
  echo "Unpacking frozen gems for Customers API."
  (cd /opt/smartdc/capi; PATH=/opt/local/bin:$PATH /opt/local/bin/rake gems:deploy -f /opt/smartdc/capi/Rakefile)
fi

if [[ ! -e /opt/smartdc/capi/config/unicorn.smf ]]; then
  echo "Creating Customers API Unicorn Manifest."
  /opt/local/bin/ruby18 -rerb -e "user='jill';group='jill';app_environment='production';application='capi'; working_directory='/opt/smartdc/capi'; puts ERB.new(File.read('/opt/smartdc/capi/config/deploy/unicorn.smf.erb')).result" > /opt/smartdc/capi/config/unicorn.smf
  chown jill:jill /opt/smartdc/capi/config/unicorn.smf
fi

if [[ ! -e /opt/smartdc/capi/config/unicorn.conf ]]; then
  echo "Creating Customers API Unicorn Configuration file."
  /opt/local/bin/ruby18 -rerb -e "app_port='8080'; worker_processes=1; working_directory='/opt/smartdc/capi'; application='capi'; puts ERB.new(File.read('/opt/smartdc/capi/config/unicorn.conf.erb')).result" > /opt/smartdc/capi/config/unicorn.conf
  chown jill:jill /opt/smartdc/capi/config/unicorn.conf
fi

if [[ -z $(cat /opt/smartdc/capi/config/database.yml|grep capi) ]]; then
  echo "Configuring Customers API Database."
  cat > /opt/smartdc/capi/config/database.yml <<CAPI_DB

:production: &prod
  :adapter: postgres
  :database: capi
  :username: postgres
  :password: postgres
  :host: $POSTGRES
  :encoding: UTF-8

CAPI_DB
fi

if [[ ! -e /opt/smartdc/capi/tmp/pids ]]; then
  su - jill -c "mkdir -p /opt/smartdc/capi/tmp/pids"
fi


echo "Auto Upgrading Customers API Database."
su - jill -c "cd /opt/smartdc/capi; RACK_ENV=production /opt/local/bin/rake standalone:db:autoupgrade -f /opt/smartdc/capi/Rakefile"
sleep 1
#echo "Auto Upgrading Customers API Database."
#su - jill -c "cd /opt/smartdc/capi; RACK_ENV=production /opt/local/bin/rake standalone:db:autoupgrade -f /opt/smartdc/capi/Rakefile"
#sleep 1

if [[ -z $(/usr/bin/svcs -a|grep capi) ]]; then
  echo "Importing Customers API Unicorn Manifest"
  /usr/sbin/svccfg import /opt/smartdc/capi/config/unicorn.smf
  sleep 1
fi

# Ensure everything in /opt/smartdc is owned by jill
chown -R jill:jill /opt/smartdc

# fix perms on /home
chown root:root /home
chmod 0555 /home

## Setup and call the verify script

echo "postgres" > /tmp/pgpasswd
(cd /opt/smartdc/capi && ./script/verify_setup.sh)
(cd /opt/smartdc/capi && RACK_ENV=production rake dev:fake_data) 2>&1 | tee /tmp/fake_data.output
grep "Customer URL for zones creation" /tmp/fake_data.output | sed -e "s/^.*POST //" | sed -e "s/'$//" > /root/customer.url
rm -f /tmp/fake_data.output /tmp/pgpasswd
#echo "postgres" > /tmp/pgpasswd
#(cd /opt/smartdc/capi && ./script/verify_setup.sh)
#(cd /opt/smartdc/capi && RACK_ENV=production rake dev:fake_data) 2>&1 | tee /tmp/fake_data.output
#grep "Customer URL for zones creation" /tmp/fake_data.output | sed -e "s/^.*POST //" | sed -e "s/'$//" > /root/customer.url
#rm -f /tmp/fake_data.output /tmp/pgpasswd

