#!/bin/bash

echo "99 finalizing billapi zone"

echo "Installing local node.js"
cd /opt/smartdc
/usr/bin/gtar -z -m -xf /opt/tmp/node.tgz
cd -
/usr/bin/rm -fr /opt/tmp
/usr/bin/chown -R root:root /opt/smartdc

echo "Generating SSL Certificate"
/opt/local/bin/openssl req -x509 -nodes -subj '/CN=*' -newkey rsa:2048 -keyout /opt/smartdc/billapi/ssl/key.pem -out /opt/smartdc/billapi/ssl/cert.pem -days 365


echo "Creating HTTP Server SMF manifest"
cat > /opt/smartdc/billapi/billapi_manifest.xml <<HERE
<?xml version="1.0"?>
<!DOCTYPE service_bundle SYSTEM "/usr/share/lib/xml/dtd/service_bundle.dtd.1">
<service_bundle type="manifest" name="billapi">
  <service name="smartdc/site/billapi" type="service" version="6.1.0">

    <create_default_instance enabled="true"/>
    <single_instance/>

    <dependency name="network" grouping="require_all" restart_on="error" type="service">
      <service_fmri value="svc:/milestone/network:default"/>
    </dependency>

    <dependency name="filesystem" grouping="require_all" restart_on="error" type="service">
      <service_fmri value="svc:/system/filesystem/local"/>
    </dependency>

    <exec_method
      type="method"
      name="start"
      exec="/opt/smartdc/node/bin/node /opt/smartdc/billapi/server.js -f /opt/smartdc/billapi/config/config.json &amp;"
      timeout_seconds="60">
      <method_context working_directory="/opt/smartdc/billapi">
        <method_credential user="nobody" group="nobody" privileges="basic,net_privaddr"/>
        <method_environment>
          <envvar name="PATH" value="/opt/smartdc/node/bin:/usr/local/bin:/opt/local/bin:/usr/bin:/usr/sbin:/bin"/>
          <envvar name="LD_PRELOAD_32" value="/usr/lib/extendedFILE.so.1" />
        </method_environment>
      </method_context>
    </exec_method>

    <exec_method type="method" name="restart" exec=":kill" timeout_seconds="60">
      <method_context working_directory="/opt/smartdc/billapi" />
    </exec_method>

    <exec_method type="method" name="stop" exec=":kill" timeout_seconds="60">
      <method_context working_directory="/opt/smartdc/billapi" />
    </exec_method>

    <property_group name="startd" type="framework">
      <propval name="ignore_error" type="astring" value="core,signal"/>
    </property_group>

    <property_group name="application" type="application">

    </property_group>

    <stability value="Stable"/>

    <template>
      <common_name>
        <loctext xml:lang="C">Billing API HTTP Server (node)</loctext>
      </common_name>
    </template>

  </service>

</service_bundle>
HERE

echo "Creating AMQP Consumer SMF manifest"
cat > /opt/smartdc/billapi/billapi_consumer_manifest.xml <<HERE
<?xml version="1.0"?>
<!DOCTYPE service_bundle SYSTEM "/usr/share/lib/xml/dtd/service_bundle.dtd.1">
<service_bundle type="manifest" name="billapi-consumer">
  <service name="smartdc/site/billapi-consumer" type="service" version="6.1.0">

    <create_default_instance enabled="true"/>
    <single_instance/>

    <dependency name="network" grouping="require_all" restart_on="error" type="service">
      <service_fmri value="svc:/milestone/network:default"/>
    </dependency>

    <dependency name="filesystem" grouping="require_all" restart_on="error" type="service">
      <service_fmri value="svc:/system/filesystem/local"/>
    </dependency>

    <exec_method
      type="method"
      name="start"
      exec="/opt/smartdc/node/bin/node /opt/smartdc/billapi/consumer.js -f /opt/smartdc/billapi/config/config.json &amp;"
      timeout_seconds="60">
      <method_context working_directory="/opt/smartdc/billapi">
        <method_credential user="nobody" group="nobody" privileges="basic,net_privaddr"/>
        <method_environment>
          <envvar name="PATH" value="/opt/smartdc/node/bin:/usr/local/bin:/opt/local/bin:/usr/bin:/usr/sbin:/bin"/>
          <envvar name="LD_PRELOAD_32" value="/usr/lib/extendedFILE.so.1" />
        </method_environment>
      </method_context>
    </exec_method>

    <exec_method type="method" name="restart" exec=":kill" timeout_seconds="60">
      <method_context working_directory="/opt/smartdc/billapi" />
    </exec_method>

    <exec_method type="method" name="stop" exec=":kill" timeout_seconds="60">
      <method_context working_directory="/opt/smartdc/billapi" />
    </exec_method>

    <property_group name="startd" type="framework">
      <propval name="ignore_error" type="astring" value="core,signal"/>
    </property_group>

    <property_group name="application" type="application">

    </property_group>

    <stability value="Stable"/>

    <template>
      <common_name>
        <loctext xml:lang="C">Billing API AMQP Consumer (node)</loctext>
      </common_name>
    </template>

  </service>

</service_bundle>
HERE

echo "Creating Report Queue manifest"
cat > /opt/smartdc/billapi/billapi_queue_manifest.xml <<HERE
<?xml version="1.0"?>
<!DOCTYPE service_bundle SYSTEM "/usr/share/lib/xml/dtd/service_bundle.dtd.1">
<service_bundle type="manifest" name="billapi-queue">
  <service name="smartdc/site/billapi-queue" type="service" version="6.1.0">

    <create_default_instance enabled="true"/>
    <single_instance/>

    <dependency name="network" grouping="require_all" restart_on="error" type="service">
      <service_fmri value="svc:/milestone/network:default"/>
    </dependency>

    <dependency name="filesystem" grouping="require_all" restart_on="error" type="service">
      <service_fmri value="svc:/system/filesystem/local"/>
    </dependency>

    <exec_method
      type="method"
      name="start"
      exec="/opt/smartdc/node/bin/node /opt/smartdc/billapi/queue.js -f /opt/smartdc/billapi/config/config.json &amp;"
      timeout_seconds="60">
      <method_context working_directory="/opt/smartdc/billapi">
        <method_credential user="nobody" group="nobody" privileges="basic,net_privaddr"/>
        <method_environment>
          <envvar name="PATH" value="/opt/smartdc/node/bin:/usr/local/bin:/opt/local/bin:/usr/bin:/usr/sbin:/bin"/>
          <envvar name="LD_PRELOAD_32" value="/usr/lib/extendedFILE.so.1" />
        </method_environment>
      </method_context>
    </exec_method>

    <exec_method type="method" name="restart" exec=":kill" timeout_seconds="60">
      <method_context working_directory="/opt/smartdc/billapi" />
    </exec_method>

    <exec_method type="method" name="stop" exec=":kill" timeout_seconds="60">
      <method_context working_directory="/opt/smartdc/billapi" />
    </exec_method>

    <property_group name="startd" type="framework">
      <propval name="ignore_error" type="astring" value="core,signal"/>
    </property_group>

    <property_group name="application" type="application">

    </property_group>

    <stability value="Stable"/>

    <template>
      <common_name>
        <loctext xml:lang="C">Billing API Report Queue (node)</loctext>
      </common_name>
    </template>

  </service>

</service_bundle>
HERE



# Apply configuration from /opt/smartdc/etc/zoneconfig now
source /opt/smartdc/bin/configure.sh

echo "Importing billapi_manifest.xml"
/usr/sbin/svccfg import /opt/smartdc/billapi/billapi_manifest.xml

echo "Importing billapi_consumer_manifest.xml"
/usr/sbin/svccfg import /opt/smartdc/billapi/billapi_consumer_manifest.xml

echo "Importing billapi_queue_manifest.xml"
/usr/sbin/svccfg import /opt/smartdc/billapi/billapi_queue_manifest.xml

echo "Enablig service billapi"
/usr/sbin/svcadm enable smartdc/site/billapi
echo "Enablig service billapi-consumer"
/usr/sbin/svcadm enable smartdc/site/billapi-consumer
echo "Enablig service billapi-queue"
/usr/sbin/svcadm enable smartdc/site/billapi-queue

