-record(rpbbucketprops, {n_val, allow_mult}).
-record(rpblink, {bucket, key, tag}).
-record(rpbpair, {key, value}).
-record(rpbcontent, {value, content_type, charset, content_encoding, vtag, links, last_mod, last_mod_usecs, usermeta}).
-record(rpbmapredresp, {phase, response, done}).
-record(rpbmapredreq, {request, content_type}).
-record(rpbsetbucketreq, {bucket, props}).
-record(rpbgetbucketresp, {props}).
-record(rpbgetbucketreq, {bucket}).
-record(rpblistkeysresp, {keys, done}).
-record(rpblistkeysreq, {bucket}).
-record(rpblistbucketsresp, {buckets}).
-record(rpbdelreq, {bucket, key, rw}).
-record(rpbputresp, {content, vclock}).
-record(rpbputreq, {bucket, key, vclock, content, w, dw, return_body}).
-record(rpbgetresp, {content, vclock}).
-record(rpbgetreq, {bucket, key, r}).
-record(rpbgetserverinforesp, {node, server_version}).
-record(rpbsetclientidreq, {client_id}).
-record(rpbgetclientidresp, {client_id}).
-record(rpberrorresp, {errmsg, errcode}).
