#!/usr/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#

set -o xtrace

PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

role=dcapi
app_name=$role

# This includes the fatal function and downloads and installs files.
source /var/svc/setup.common

# Cookie to identify this as a SmartDC zone and its role
mkdir -p /var/smartdc/dcapi

# Install DCAPI
mkdir -p /opt/smartdc/dcapi
chown -R nobody:nobody /opt/smartdc/dcapi

# Setup HAProxy user/group
/usr/sbin/groupadd haproxy
/usr/sbin/useradd -d /tmp -g haproxy -s /usr/bin/false haproxy
/usr/bin/passwd -N haproxy

echo "Generating SSL Certificate"
/opt/local/bin/openssl req -x509 -nodes -subj '/CN=*' -newkey rsa:2048 -keyout /opt/smartdc/dcapi/etc/key.pem -out /opt/smartdc/dcapi/etc/cert.pem -days 365

# Add node_modules/bin to PATH
echo "" >>/root/.bashrc
echo "export PATH=\$PATH:/opt/smartdc/dcapi/node_modules/.bin" >>/root/.bashrc


/opt/smartdc/bin/configure || fatal "Unable to configure zone."


touch /var/svc/setup_complete
echo "setup done"
(sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &

exit 0

