#!/usr/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#

set -o xtrace

PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

role=ca
app_name=$role

# This includes the fatal function and downloads and installs files.
source /var/svc/setup.common

# Cookie to identify this as a SmartDC zone and its role
mkdir -p /var/smartdc/ca
mkdir -p /opt/smartdc/ca-data

data_ds=`zfs list -H -oname | grep "data$"`
[ -n "$data_ds" ] && zfs set mountpoint=/var/smartdc/ca $data_ds

echo "finalizing ca zone"

npm install --user=root --no-rebuild-bundle -g /pkg/cabase.tar.gz
npm install --user=root --no-rebuild-bundle -g /pkg/caaggsvc.tar.gz
npm install --user=root --no-rebuild-bundle -g /pkg/castashsvc.tar.gz
npm install --user=root --no-rebuild-bundle -g /pkg/caconfigsvc.tar.gz

/opt/smartdc/bin/configure || fatal "Failed to run configure for zone."

touch /var/svc/setup_complete
echo "setup done"
(sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &

exit 0
