#!/usr/bin/bash
#
# Copyright (c) 2011, Joyent Inc. All rights reserved.
#

set -o xtrace

PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

role=amon
app_name=$role
assets_ip=${ASSETS_IP} # populated by user-script

# This includes the fatal function and downloads and installs files.
source /var/svc/setup.common

# Add amon master's bin dir to the PATH for convenience functions.
echo "" >>/root/.bashrc
echo "export PATH=\$PATH:/opt/smartdc/amon/bin" >>/root/.bashrc

# run the configuration
/opt/smartdc/bin/configure || fatal "unable to configure"

touch /var/svc/setup_complete
echo "setup done"
(sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &

exit 0
