#!/usr/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#

if [[ $# != 2 ]]; then
    echo "Usage: $0 <zone_name> <target_directory>"
    exit 1
fi

ROLE=cloudapi
UUID=$1
TARGET_DIR=$2
CFG_FILE=/zones/${UUID}/root/opt/smartdc/cloudapi/cfg/config.json
PLUG_DIR=/zones/${UUID}/root/opt/smartdc/cloudapi/plugins

if [[ ! -d "${TARGET_DIR}" ]]; then
    echo "Invalid directory: '${TARGET_DIR}'"
    exit 1
fi

# Create the backup directory:
mkdir -p ${TARGET_DIR}/${ROLE}

echo "==> Saving config file for zone '${ZONE}'"
[ -f $CFG_FILE ] && cp $CFG_FILE ${TARGET_DIR}/${ROLE}

if [ -d $PLUG_DIR ]; then
    echo "==> Saving plugins for zone '${ROLE}'"
    mkdir -p ${TARGET_DIR}/${ROLE}/plugins
    (cd ${PLUG_DIR} && cp -p * ${TARGET_DIR}/${ROLE}/plugins)
fi

echo "==> Done!"
exit 0
