#!/usr/bin/bash
#
# Copyright (c) 2012, Joyent Inc., All rights reserved.
#

if [[ $# != 2 ]]; then
    echo "Usage: $0 <zone_name> <src_directory>"
    exit 1
fi

ZONE=cloudapi
SRC_DIR=$2
CFG_FILE=/zones/cloudapi/root/opt/smartdc/cloudapi/cfg/config.json
PLUG_DIR=/zones/cloudapi/root/opt/smartdc/cloudapi/plugins
SSL_DIR=/zones/cloudapi/root/opt/smartdc/cloudapi/ssl

# Older backups may not have had this zone
if [[ ! -d "${SRC_DIR}/${ZONE}" ]]; then
	echo "Warning, backup missing $ZONE"
	echo "==> Done"
	exit 0
fi

if [[ ! -f "${SRC_DIR}/${ZONE}/config.json" ]]; then
	echo "Warning, backup missing config file for $ZONE"
	echo "==> Done"
	exit 0
fi

echo "==> Restoring config file for zone '${ZONE}'"
cp ${SRC_DIR}/${ZONE}/config.json $CFG_FILE

mkdir -p $PLUG_DIR
if [[ -d "${SRC_DIR}/${ZONE}/plugins" ]]; then
    for i in `ls ${SRC_DIR}/${ZONE}/plugins`
    do
        if [ ! -f $PLUG_DIR/$i ]; then
            echo "==> Restoring plugin $i for zone '${ZONE}'"
            cp -p ${SRC_DIR}/${ZONE}/plugins/$i $PLUG_DIR
        fi
    done
fi

if [[ -d "${SRC_DIR}/${ZONE}/ssl" ]]; then
    echo "==> Restoring SSL certs for zone '${ZONE}'"
    mkdir -p $SSL_DIR
    cp -p ${SRC_DIR}/${ZONE}/ssl/* $SSL_DIR
fi

echo "==> Done"
exit 0
