#!/usr/bin/bash

# This script runs with the $CONFIG_assets_ip variable set to the assets zone
# IP address.  Its up to this script to pull down the rest of the files it
# needs from the assets zone and setup the zone for the given role.  This
# script is run in the background by the mdata svc so its ok if it takes
# a little while to install all of the pkgs.

PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

role=cloudapi
app_name=$role

cd /var/svc

curl -k -o zoneconfig -s $CONFIG_assets_ip:/extra/$role/zoneconfig
curl -k -o hn_config -s $CONFIG_assets_ip:/extra/$role/hn_config
curl -k -o hn_generic -s $CONFIG_assets_ip:/extra/$role/hn_generic

# We need some of the headnode config, but don't leave the files around
. /var/svc/hn_config
. /var/svc/hn_generic
rm -f /var/svc/hn_config /var/svc/hn_generic
# Load up the config values
. /var/svc/zoneconfig

# The user-script is downloaded and executed on every zone boot. We take
# advantage of this to maintain the cached config values post-setup.
if [ -e /var/svc/setup_complete ]; then
	oldpw=`nawk '{
	    if ($1 == "\"mapi\":")
		found = 1
	    else if ($1 == "},")
		found = 0

	    if (found && $1 == "\"password\":")
		print substr($2, 2, length($2) - 3)
	}' /opt/smartdc/cloudapi/cfg/config.json`
	[ "$mapi_http_admin_pw" == "$oldpw" ] && exit 0

	echo "Updating cloudapi configuration"
	nawk -v p=$mapi_http_admin_pw '{
	    if ($1 == "\"capi\":" || $1 == "\"mapi\":")
		change = 1
	    else if ($1 == "},")
		change = 0

	    if (change && $1 == "\"password\":")
		printf("    \"password\": \"%s\",\n", p)
	    else
		print $0
	}' /opt/smartdc/cloudapi/cfg/config.json \
	 > /opt/smartdc/cloudapi/cfg/config.json.new
	mv /opt/smartdc/cloudapi/cfg/config.json.new \
	   /opt/smartdc/cloudapi/cfg/config.json
	svcadm restart cloudapi
	exit 0
fi

# Setup the zone
curl -k -o pkgsrc -s $CONFIG_assets_ip:/extra/$role/pkgsrc
curl -k -o fs.tar.bz2 -s $CONFIG_assets_ip:/extra/$role/fs.tar.bz2

# Unpack fs.tar and copy files into proper locations within the zone
mkdir /.stage
echo "unpack fs.tar"
(cd /.stage; bzcat /var/svc/fs.tar.bz2 | tar xbf 512 -) 
rm -f /var/svc/fs.tar.bz2
echo "install root"
(cd /.stage/root; tar cbf 512 - *) | (cd /; tar xbf 512 -)
rm -rf /.stage

for i in `cat /var/svc/pkgsrc`
do
	pkgin -y install $i
done

# XXX is net1 external nic?
EXT_IPADDR=`ifconfig net1 | nawk '{if ($1 == "inet") print $2}'`
CLOUDAPI_EXTERNAL_URL="https://$EXT_IPADDR"

echo "finalizing cloudapi zone"

echo "Installing local node.js"
cd /opt/smartdc
/usr/bin/gtar -z -m -xf /opt/tmp/node.tgz
cd -
/usr/bin/rm -fr /opt/tmp
/usr/bin/chown -R root:root /opt/smartdc

echo "Generating SSL Certificate"
/opt/local/bin/openssl req -x509 -nodes -subj '/CN=*' -newkey rsa:2048 -keyout /opt/smartdc/cloudapi/ssl/key.pem -out /opt/smartdc/cloudapi/ssl/cert.pem -days 365

echo "Creating SMF manifest"
cat > /opt/smartdc/cloudapi/cloudapi_manifest.xml <<HERE
<?xml version="1.0"?>
<!DOCTYPE service_bundle SYSTEM "/usr/share/lib/xml/dtd/service_bundle.dtd.1">
<service_bundle type="manifest" name="cloudapi">
  <service name="smartdc/site/cloudapi" type="service" version="6.1.0">

    <create_default_instance enabled="true"/>
    <single_instance/>

    <dependency name="network" grouping="require_all" restart_on="error" type="service">
      <service_fmri value="svc:/milestone/network:default"/>
    </dependency>

    <dependency name="filesystem" grouping="require_all" restart_on="error" type="service">
      <service_fmri value="svc:/system/filesystem/local"/>
    </dependency>

    <exec_method
      type="method"
      name="start"
      exec="/opt/smartdc/node/bin/node /opt/smartdc/cloudapi/server.js &amp;"
      timeout_seconds="60">
      <method_context working_directory="/opt/smartdc/cloudapi">
        <method_credential user="nobody" group="nobody" privileges="basic,net_privaddr"/>
        <method_environment>
          <envvar name="PATH" value="/opt/smartdc/node/bin:/usr/local/bin:/opt/local/bin:/usr/bin:/usr/sbin:/bin"/>
          <envvar name="LD_PRELOAD_32" value="/usr/lib/extendedFILE.so.1" />
        </method_environment>
      </method_context>
    </exec_method>

    <exec_method type="method" name="restart" exec=":kill" timeout_seconds="60">
      <method_context working_directory="/opt/smartdc/cloudapi" />
    </exec_method>

    <exec_method type="method" name="stop" exec=":kill" timeout_seconds="60">
      <method_context working_directory="/opt/smartdc/cloudapi" />
    </exec_method>

    <property_group name="startd" type="framework">
      <propval name="ignore_error" type="astring" value="core,signal"/>
    </property_group>

    <property_group name="application" type="application">

    </property_group>

    <stability value="Stable"/>

    <template>
      <common_name>
        <loctext xml:lang="C">Cloudapi daemon (node)</loctext>
      </common_name>
    </template>

  </service>

</service_bundle>
HERE

cat > /opt/smartdc/cloudapi/cfg/config.json <<HERE
{
  "siteName": "${CLOUDAPI_EXTERNAL_URL}",
  "port": 443,
  "cert": "./ssl/cert.pem",
  "key": "./ssl/key.pem",
  "logLevel": 4,
  "capi": {
    "uri": "${CAPI_URL}",
    "username": "${CAPI_HTTP_ADMIN_USER}",
    "password": "${CAPI_HTTP_ADMIN_PW}",
    "authCache": {
      "size": 100,
      "expiry": 60
    },
    "accountCache": {
      "size": 100,
      "expiry": 300
    }
  },
  "mapi": {
    "uri": "${MAPI_URL}",
    "username": "${MAPI_HTTP_ADMIN_USER}",
    "password": "${MAPI_HTTP_ADMIN_PW}",
    "datasetCache": {
      "size": 100,
      "expiry": 300
    }
  },
  "ca": {
    "uri": "${CA_URL}"
  },
  "rabbitmq": {
    "host": "${RABBIT_IP}",
    "user": "guest",
    "password": "guest",
    "vhost": "/"
  },
  "datacenters": {
    "${DATACENTER_NAME}": "${CLOUDAPI_EXTERNAL_URL}"
  },
  "preProvisionHook": {
    "plugin": "./plugins/capi_limits",
    "enabled": true,
    "config": {
      "datacenter": "${DATACENTER_NAME}",
      "defaults": {
        "smartos": 1,
        "nodejs": 1,
        "ubuntu": 1
      }
    }
  },
  "postProvisionHook": {
    "plugin": "./plugins/machine_email",
    "enabled": false,
    "config": {
      "sendmail": "/opt/local/sbin/sendmail -i",
      "from": "support@joyent.com",
      "subject": "Your SmartDataCenter machine is provisioning",
      "body": "Check /my/machines for updates"
    }
  },
  "userThrottles": {
    "all": {
      "username": true,
      "burst": 30,
      "rate": 10,
      "overrides": {
        "${CAPI_ADMIN_LOGIN}": {
          "burst": 0,
          "rate": 0
        }
      }
    },
    "analytics": {
      "username": true,
      "burst": 1000,
      "rate": 100,
      "overrides": {
        "${CAPI_ADMIN_LOGIN}": {
          "burst": 0,
          "rate": 0
        }
      }
    }
  }
}
HERE

echo Importing cloudapi_manifest.xml
/usr/sbin/svccfg import /opt/smartdc/cloudapi/cloudapi_manifest.xml

echo Enablig service cloudapi
/usr/sbin/svcadm enable smartdc/site/cloudapi

touch /var/svc/setup_complete
echo "setup done"
