#!/usr/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#

set -o xtrace

PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

role=cloudapi

# This includes the fatal function and downloads and installs files.
source /var/svc/setup.common

# Cookie to identify this as a SmartDC zone and its role
mkdir -p /var/smartdc/$role
mkdir -p /opt/smartdc/$role/ssl

echo "Installing local node.js"
mkdir -p /opt/smartdc/$role/cfg
cd -
/usr/bin/chown -R root:root /opt/smartdc

echo "Generating SSL Certificate"
/opt/local/bin/openssl req -x509 -nodes -subj '/CN=*' -newkey rsa:2048 \
    -keyout /opt/smartdc/$role/ssl/key.pem \
    -out /opt/smartdc/$role/ssl/cert.pem -days 365

# Setup HAProxy user/group
/usr/sbin/groupadd haproxy
/usr/sbin/useradd -d /tmp -g haproxy -s /usr/bin/false haproxy
/usr/bin/passwd -N haproxy

# Add build/node/bin and node_modules/.bin to PATH
echo "" >>/root/.bashrc
echo "export PATH=\$PATH:/opt/smartdc/$role/build/node/bin:/opt/smartdc/$role/node_modules/.bin" >>/root/.bashrc

# do configuration now.
/opt/smartdc/bin/configure || fatal "Unable to configure $role zone"

touch /var/svc/setup_complete
echo "setup done"
(sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &

exit 0
