#!/usr/bin/bash
#

# Important! This is just a place-holder until we rewrite in node.
#


if [ "$TRACE" != "" ]; then
    export PS4='${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -o xtrace
fi

if [[ ! -f /opt/smartdc/bin/libdc.sh ]]; then
    echo "fatal: unable to find libdc.sh"
    exit 1
fi

source /opt/smartdc/bin/libdc.sh

path=$1
if [[ -z ${path} ]]; then
    cat <<EOF
error: no PATH argument given

Usage:
        $0 PATH [EXTRA-CURL-ARGS]

EOF
    exit 1
fi

workflow "$@" > /tmp/workflow.$$
if grep "HTTP/1.1 204 No Content" /tmp/workflow.$$ >/dev/null 2>&1; then
    # we have no content so no point feeding through json (it'll fail)
    /bin/true
else
    json -q < /tmp/workflow.$$
fi

exit 0
