#!/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#
# Convenience wrapper for calling DSAPI (the Dataset API).
#

if [[ -n "$TRACE" ]]; then
    export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -o xtrace
fi
set -o errexit
set -o pipefail


# Arguments.
verbose=0
if [ "$1" == "-v" ]; then
    shift
    verbose=1
fi
path=$1
if [[ -z "$path" ]]; then
    echo "error: no PATH argument given"
    echo "Usage: sdc-dsapi [-v] PATH [EXTRA-CURL-ARGS]"
    exit 1
fi
shift;
JSON=$(which json 2>/dev/null || true)


# Determine DSAPI URL.
if [[ -f /lib/sdc/config.sh ]]; then
    source /lib/sdc/config.sh
    load_sdc_config
    if [[ -z "$DSAPI_URL" ]]; then
        DSAPI_URL=$CONFIG_dsapi_url
    fi
fi
if [[ -z "$DSAPI_URL" ]]; then
    DSAPI_URL=https://datasets.joyent.com
fi

# Note: the 'echo' doesn't show the real quoting of args.
[ "$verbose" == "1" ] && echo "# curl -k -sS -i --url $DSAPI_URL$path $@" >&2
if [[ ! -x "$JSON" ]]; then
    curl -k -sS -i --url "$DSAPI_URL$path" "$@"
    echo ""
else
    curl -k -sS -i --url "$DSAPI_URL$path" "$@" | json -q
fi
