#!/usr/bin/bash
#

# Important! This is just a place-holder until we rewrite in node.
#

if [ "$TRACE" != "" ]; then
    export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -o xtrace
fi

if [[ ! -f /opt/smartdc/bin/libdc.sh ]]; then
    echo "fatal: unable to find libdc.sh"
    exit 1
fi
source /opt/smartdc/bin/libdc.sh

command=$1
shift

usage()
{
    cat <<EOF

Usage:
        $0 <sub-command> [options]

Sub-commands:

        list           - list all servers in this DC
        setup <uuid>   - setup a new server in this DC
        sysinfo <uuid> - output the latest \`sysinfo\` from the server

EOF
    exit 1
}

server_list()
{
    servers=$(cnapi /servers | json -H -a uuid)
    if [[ -n ${servers} ]]; then
        # this sets the variables:
        #
        #  nic_UUID_<tag>=<IP>
        #
        # with uuid's dashes changed to underscore to meet bash's variable name requirements.
        for data in $(napi /nics?belongs_to_type=server | json -H -e \
            'this.nicy = this.nic_tags_provided ? this.nic_tags_provided.join(",") : ""' \
            -d '|' -a nicy ip belongs_to_uuid); do
            if [[ -n ${data} ]]; then
                tags=$(echo "${data}" | cut -d '|' -f1)
                ip=$(echo "${data}" | cut -d '|' -f2)
                uuid=$(echo "${data}" | cut -d '|' -f3 | tr '-' '_')
                for tag in $(echo ${tags} | sed -e 's/,/ /g'); do
                    if [[ -n ${tag} && -n ${ip} && -n ${uuid} ]]; then
                        eval "nic_${uuid}_${tag}=${ip}"
                    fi
                done
            fi
        done

        printf "%-20s %-36s  %-5s  %7s  %15s\n" \
            "HOSTNAME" "UUID" "SETUP" "RAM" "ADMIN_IP"
        for uuid in $(cnapi /servers | json -H -a uuid); do
            # if someone has a better way to do this, it'd be a appreciated.
            admin_ip=$(eval echo \${nic_$(echo ${uuid} | tr '-' '_')_admin})
            [[ -z ${admin_ip} ]] && admin_ip="-"
                #| json -H -e 'if this.memory_total_bytes { memory_total_bytes=parseInt(memory_total_bytes) / (1024 * 1024) } else { memory_total_bytes=0 }' \
            data=$(cnapi /servers/${uuid} \
                | json -H -e 'memory_total_bytes = (this.hasOwnProperty("memory_total_bytes") ? memory_total_bytes : 0)' \
                -e 'memory_total_bytes=parseInt(memory_total_bytes / (1024 * 1024))' \
                -a hostname setup memory_total_bytes)
            hostname=${data%% *}
            setup=$(echo ${data} | cut -d ' ' -f2)
            ram=${data##* }

            printf "%-20s %36s  %-5s  %7s  %15s\n" \
                "${hostname}" "${uuid}" "${setup}" "${ram}" "${admin_ip}"
        done
    fi
}

server_setup()
{
    server_uuid=$1

    if [[ -n $2 ]]; then
        usage
    fi

    # Time for setup!
    cnapi /servers/${server_uuid}/setup -X PUT -m 60000
}

server_sysinfo()
{
    server_uuid=$1

    if [[ -n $2 ]]; then
        usage
    fi

    info=$(cnapi /servers/${server_uuid})
    if [[ -n ${info} ]]; then
        echo "${info}" | json -H sysinfo | json
    fi
}

if [[ -z ${command} ]]; then
    usage
fi

case ${command} in
list)
    server_list "$@"
;;
setup)
    server_setup "$@"
;;
sysinfo)
    server_sysinfo "$@"
;;
*)
    echo "Unknown command: ${command}" >&2
    usage
;;
esac

exit 0
