#!/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#
# Allows you to login to a smartdc_role zone by name (or partial name)
#
# Future Enhancements:
#   - add support to talk to MAPI and add an 'ssh <CN>' prefix if the zone is
#     running on a CN.
#

. /lib/sdc/config.sh
load_sdc_config

admin_uuid=${CONFIG_ufds_admin_uuid}
zone=$1
shift

if [[ -z ${admin_uuid} ]]; then
    echo "Unable to find UUID for admin."
    exit 1
fi

if [[ -z ${zone} ]]; then
    echo "Usage: $0 <zone role>"
    exit 2
fi

zone_uuid=$(vmadm lookup -1 owner_uuid=${admin_uuid} tags.smartdc_role=~^${zone})
if [[ -z ${zone_uuid} ]]; then
    echo "Did not find exactly 1 zone matching: ${zone}"
    exit 1
fi

exec zlogin ${zone_uuid} $*
