#!/bin/bash
#
# Copyright (c) 2013, Joyent, Inc., All rights reserved.
#

PATH=/usr/bin:/usr/sbin:/image/usr/sbin:/opt/smartdc/bin:/smartdc/bin
export PATH

function fatal
{
    msg=$1

    echo "ERROR: ${msg}" >/dev/stderr
    exit 1
}

#
# post-upgrade only runs on headnodes.
#
[[ `sysinfo | json '["Boot Parameters"].headnode'` != "true" ]] && \
    fatal "this command can only be run on the headnode"

COMMIT=0
WRITABLE=0
REPL_STAT=0
while getopts "crw" opt
do
	case "$opt" in
		r)	REPL_STAT=1;;
		w)	WRITABLE=1;;
		c)	COMMIT=1;;
		*)	fatal "invalid option";;
	esac
done

if [[ $WRITABLE == 1 ]]; then
    zonename=`vmadm list -H -o uuid,tags.smartdc_role | \
        nawk '/cloudapi/{print $1}'`

    [[ -z "$zonename" ]] && fatal "no cloudapi zone"

    echo "Enabling read-write mode in cloudapi"

    cfgfile=/zones/$zonename/root/opt/smartdc/cloudapi/etc/cloudapi.cfg

    nawk '{
        if ($1 == "\"read_only\":")
             printf("    \"read_only\": false,\n")
        else
            print $0
    }' $cfgfile >$cfgfile.new
    cp $cfgfile $cfgfile.bak
    cp $cfgfile.new $cfgfile
    rm -f $cfgfile.new

    zlogin $zonename svcadm restart cloudapi

    exit 0
fi

if [[ $REPL_STAT == 1 ]]; then
    if [[ $CONFIG_ufds_is_master == "true" ]]; then
        echo "This is the UFDS master"
        exit 0
    fi

    ufds_uuid=`vmadm lookup -1 tags.smartdc_role=ufds`

    log=/var/svc/log/smartdc-application-ufds-replicator:default.log

    changelog_num=`nawk '{
            pos = index($0, "Updated changenumber to")
            if (pos == 0)
                next
            s = substr($0, pos + 24)
            pos = index(s, "\"") - 1
            n = substr(s, 1, pos)
        }
        END {print n}' /zones/$ufds_uuid/root/$log`

    egrep -s "No new changelog entries" /zones/$ufds_uuid/root/$log
    if [[ $? == 0 ]]; then
        echo "Replication is caught up"
        exit 0
    fi

    . /lib/sdc/config.sh
    load_sdc_config

    # determine approx. how many changelog entries we need to replicate
    echo "PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin:/opt/smartdc/ufds/build/node/bin:/opt/smartdc/ufds/node_modules/.bin" \
            >/zones/$ufds_uuid/root/tmp/cnt
    echo "LDAPTLS_REQCERT=allow ldapsearch -x -LLL" \
        "-H ldaps://$CONFIG_ufds_remote_ip -D $CONFIG_ufds_ldap_root_dn" \
        "-w $CONFIG_ufds_ldap_root_pw -b cn=changelogcount" \
        "'(&(objetclass=*))'" >>/zones/$ufds_uuid/root/tmp/cnt

    totcl=`zlogin $ufds_uuid bash /tmp/cnt | \
        nawk '{if ($1 == "count:") print $2}'`

    [[ -z "$totcl" || $totcl == 0 ]] && totcl=1

    pct=$((($changelog_num * 100) / $totcl))
    echo "$pct% of user data is replicated"

    exit 0
fi

if [[ $COMMIT == 1 ]]; then
    [ ! -d /var/usb_rollback ] && \
        fatal "nothing to commit: data does not exist"

    echo "-----------------------------------------------------------------"
    echo "Warning:"
    echo "This command will commit the upgrade and prevent future rollback."
    echo "-----------------------------------------------------------------"
    echo -n "Enter 'y' to continue: "
    read val
    [[ "$val" != "y" ]] && exit 0

    # Enable the new zfs features that we know about
    zpool set feature@async_destroy=enabled zones
    zpool set feature@empty_bpobj=enabled zones
    zpool set feature@lz4_compress=enabled zones
    zpool set feature@filesystem_limits=enabled zones
    zfs set compression=lz4 zones/cores

    for i in `zfs list -o name -H -t snapshot | egrep "rollback$"`
    do
        zfs destroy $i
    done

    for i in `zfs list -o name -H | egrep "_rollback$"`
    do
        zfs destroy -r $i
    done

    # We'd like to do the following:
    #    zfs destroy -r zones/pre-upgrade
    # but that will fail since the portal zone's snapshot & clone are still
    # needed. We've already renamed the portal zone, so just cleanup the
    # things we don't need.
    for i in `zfs list -o name | egrep "zones/pre-upgrade/[a-z][^-/]*$"`
    do
        origin=`zfs list -H -o origin $i`
        zfs destroy -r $i
        zfs destroy $origin
    done

    rm -rf /var/usb_rollback

    zpool upgrade zones

    # Skip this, not really needed and the key is almost full so there will
    # be no room for a new platform.
    #
    # echo "Syncing datasets back to the USB key, this will take a while"
    # /usbkey/scripts/mount-usb.sh
    # (cd /usbkey/datasets && rsync -a * /mnt/usbkey/datasets)
    # umount /mnt/usbkey
fi

exit 0
