#!/usr/bin/bash
#

# Important! This is just a place-holder until we rewrite in node.
#


if [ "$TRACE" != "" ]; then
    export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
    set -o xtrace
fi

if [[ ! -f /opt/smartdc/bin/libdc.sh ]]; then
    echo "fatal: unable to find libdc.sh"
    exit 1
fi

source /opt/smartdc/bin/libdc.sh

path=$1
if [[ -z ${path} ]]; then
    cat <<EOF
error: no PATH argument given

Usage:
        $0 PATH [EXTRA-CURL-ARGS]

EOF
    exit 1
fi

resource=$(echo ${path}|cut -d'/' -f2)

case "$resource" in
  "jobs" | "workflows") workflow "$@" | json -H -q
    ;;
  "vms") vmapi "$@" | json -q
    ;;
  "servers") cnapi "$@" | json -q
    ;;
  "nics" | "nic_tags" | "networks") napi "$@" | json -q
    ;;
  *) echo "Unknown request PATH"
    ;;
esac


exit 0
