#!/usr/bin/bash

#
# Copyright (c) 2013, Joyent, Inc. All rights reserved.
# This backs up the SDC Manatee zone datasets and the USB config.
#

unset LD_LIBRARY_PATH
PATH=/usr/bin:/usr/sbin:/opt/smartdc/bin
export PATH

# This writes xtrace output and anything redirected to LOGFD to the log file.
LOGFD=4
exec 4>/tmp/backuplog.$$
export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
export BASH_XTRACEFD=${LOGFD}
set -o xtrace
set -o pipefail
set -o errexit

echo "logs at /tmp/backuplog.$$"

usage()
{
	printf "usage: $(basename $0) \n" >/dev/stderr
	exit 1
}

warn()
{
	printf "Warning: %s\n" "$1" >/dev/stderr
}

fatal()
{
	printf "Error: %s\n" "$1" >/dev/stderr
	exit 1
}

cleanup()
{
	cd /zones
	rm -rf $destdir
}

#
# Main body
#

# Load config variables with CONFIG_ prefix
. /lib/sdc/config.sh
load_sdc_config

if [[ `sysinfo | json '["Boot Parameters"].headnode'` != "true" ]]
then
	fatal "backup can only be run from the headnode"
fi


destdir=/zones/backups/$(uuid -v4)

trap cleanup EXIT

mkdir -p ${destdir} || fatal "unable to create backup directory $destdir"

echo "Backing up Manatee"
manatee=$(sdc-manatee-stat | json sdc.primary.zoneId)
/zones/$manatee/root/opt/smartdc/manatee/bin/manatee-backup.sh $destdir/manatee.zfs

echo "Backing up USB Key Config"
cp /usbkey/config $destdir/usbkey.confg

#XXX backup local images or just have local images go to manta?

echo "Creating backup file"
(cd $destdir && tar cbfE 512 - *) | gzip >$destdir/backup.tgz || \
    fatal "writing to file $destdir/backup.tgz"

fname=/zones/backups/backup-$(date +%Y-%m-%d-%H-%M-%S).tgz
echo "Moving backup file to destination"
mv $destdir/backup.tgz $fname || fatal "writing to file $fname"

cleanup

sz=`ls -lh $fname | nawk '{print $5}'`
echo "The backup file (size $sz) is $fname"

[ "$destdir" == "/zones" ] && \
    echo "Copy or move this file to your backup medium."

exit 0
