#!/usr/bin/bash
#
# Copyright (c) 2012 Joyent Inc., All rights reserved.
#

export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
set -o xtrace

PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

role=imgapi

# This includes the fatal function and downloads and installs files.
source /var/svc/setup.common

# Cookie to identify this as a SmartDC zone and its role
mkdir -p /var/smartdc/$role

# Reload zoneconfig variables
eval $(cat /opt/smartdc/etc/zoneconfig)

# Add build/node/bin and node_modules/.bin to PATH
echo "" >>/root/.profile
echo "export PATH=/opt/smartdc/$role/build/node/bin:/opt/smartdc/$role/node_modules/.bin:\$PATH" >>/root/.profile
LOGNAME=root . /root/.profile

/opt/smartdc/bin/configure || fatal "Unable to configure zone."

# Install Amon monitor and probes for IMGAPI.
TRACE=1 /opt/smartdc/imgapi/bin/imgapi-amon-install

# Add imgapi SSH key to UFDS
UFDS_ADMIN_IP=$(json -f ${METADATA} ufds_admin_ip)
UFDS_LDAP_ROOT_DN=$(json -f ${METADATA} ufds_ldap_root_dn)
UFDS_LDAP_ROOT_PW=$(json -f ${METADATA} ufds_ldap_root_pw)

UFDS_ADMIN_IP=$UFDS_ADMIN_IP \
    UFDS_LDAP_ROOT_DN=$UFDS_LDAP_ROOT_DN \
    UFDS_LDAP_ROOT_PW=$UFDS_LDAP_ROOT_PW \
    /opt/smartdc/imgapi/bin/imgapi-add-ssh-keys

touch /var/svc/setup_complete
echo "setup done"
(sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &

exit 0
