#!/usr/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#

PATH=/usr/bin:/usr/sbin
export PATH

if [[ $# != 2 ]]; then
    echo "Usage: $0 <zone_name> <target_directory>"
    exit 1
fi

ROLE=usageapi
UUID=$1
TARGET_DIR=$2
CFG_FILE=/zones/$UUID/root/opt/smartdc/usageapi/config/config.json

if [[ ! -d "${TARGET_DIR}" ]]; then
    echo "Invalid directory: '${TARGET_DIR}'"
    exit 1
fi

# Create the backup directory:
mkdir -p ${TARGET_DIR}/${ROLE}

echo "==> Saving config file for zone '${ROLE}'"
[ -f $CFG_FILE ] && cp $CFG_FILE ${TARGET_DIR}/${ROLE}

echo "==> Done!"
exit 0
