#!/usr/bin/bash

unset LD_LIBRARY_PATH
PATH=/usr/bin:/usr/sbin
export PATH

if [[ $# != 2 ]]; then
  echo "Usage: $0 <zone_name> <target_directory>"
  exit 1
fi

ZONE=$1
TARGET_DIR=$2
ROLE="usageapi"

CFG_FILE=/zones/${ZONE}/root/opt/smartdc/usageapi/config/config.json
DATA_DATASET=$(zfs list -H -o name | grep "${ZONE}/data$")

if [[ ! -d "${TARGET_DIR}" || ! -d ${TARGET_DIR}/${ROLE} ]]; then
  echo "Missing backup directory"
  exit 107
fi

if [[ ! -f ${TARGET_DIR}/${ROLE}/config.json ]]; then
  echo "Incomplete backup directory"
  exit 109
fi

if [[ ! -f ${TARGET_DIR}/${ROLE}/usageapi-data.zfs ]]; then
  echo "Incomplete backup directory"
  exit 110
fi

# Destroy previous dataset.
if [[ -z "${DATA_DATASET}" ]]; then
  echo "FATAL: Missing '${DATA_DATASET}' dataset"
  exit 111
fi

echo "==> Destroying dataset '${DATA_DATASET}'"
zfs destroy -r "${DATA_DATASET}"
if [[ $? -gt 0 ]]; then
  echo "FATAL: Unable to zfs destroy '${DATA_DATASET}' dataset"
  exit 112
fi

# ZFS receive the dataset from the backup:
echo "==> Receiving '${TARGET_DIR}/${ROLE}/usageapi-data.zfs'"
zfs receive -v "zones/${ZONE}/data" < "${TARGET_DIR}/${ROLE}/usageapi-data.zfs"
if [[ $? -gt 0 ]]; then
  echo "FATAL: Unable to zfs receive data dataset"
  exit 113
fi

echo "==> Restoring $ROLE config file"
cp ${TARGET_DIR}/${ROLE}/config.json $CFG_FILE
if [[ $? -ne 0 ]]; then
  echo "Error: restoring config file"
  exit 114
fi

echo "==> Done"
exit 0

