#!/usr/bin/bash

unset LD_LIBRARY_PATH
PATH=/usr/bin:/usr/sbin
export PATH

if [[ $# != 2 ]]; then
  echo "Usage: $0 <zone_name> <target_directory>"
  exit 1
fi

ZONE=$1
TARGET_DIR=$2
ROLE="usageapi"
CFG_FILE=/zones/${UUID}/root/opt/smartdc/usageapi/config/config.json

if [[ ! -f "${SRC_DIR}/${ROLE}/config.json" ]]; then
	echo "Warning, backup missing config file for $ROLE"
	echo "==> Done"
	exit 0
fi

echo "==> Restoring config file for zone '${ROLE}'"
cp ${SRC_DIR}/${ROLE}/config.json $CFG_FILE

echo "==> Done"
exit 0

