#!/usr/bin/bash
#
# Copyright (c) 2012 Joyent Inc., All rights reserved.
#

set -o xtrace

PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

role=usageapi
app_name=$role

# This includes the fatal function and downloads and installs files.
source /var/svc/setup.common

# Cookie to identify this as a SmartDC zone and its role
mkdir -p /var/smartdc/usageapi
mkdir -p /opt/smartdc/usageapi/ssl

#echo "Installing local node.js"
mkdir -p /opt/smartdc/usageapi/config
cd -
/usr/bin/chown -R root:root /opt/smartdc

echo "Generating SSL Certificate"
/opt/local/bin/openssl req -x509 -nodes -subj '/CN=*' -newkey rsa:2048 -keyout /opt/smartdc/usageapi/ssl/key.pem -out /opt/smartdc/usageapi/ssl/cert.pem -days 365

# Before we enable postgresql, we'll make a little change on the way we stop
# the service, so we can stop it without having to stop all the agents:
echo "Updating postgresql stop method"
$(/opt/local/bin/gsed -i"" -e "s/\$PGDATA stop/\$PGDATA stop -m fast/" /opt/local/share/smf/postgresql91-server/method)

/opt/smartdc/bin/configure || fatal "Failed to configure zone."

# Install Amon monitor and probes
TRACE=1 /opt/smartdc/usageapi/tools/usageapi-amon-install

touch /var/svc/setup_complete
echo "setup done"
(sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &

exit 0
