#!/bin/bash

echo "99 finalizing mapi zone"

app_name='mapi'

#
# Call symlink_ruby (imported from 97-zoneinit-common)
#
symlink_ruby

#
# Also, from 97-zoneinit-common
#
create_jill_account

# Before we enable postgresql, we'll make a little change on the way we stop
# the service, so we can stop it without having to stop all the agents:
echo "Updating postgresql stop method"
$(/opt/local/bin/gsed -i"" -e "s/\$PGDATA stop/\$PGDATA stop -m fast/" /opt/local/share/smf/method/svc-pgsql90)

# Apply configuration from /opt/smartdc/etc/zoneconfig now
source /opt/smartdc/bin/configure.sh

# Generate the agents setup script:

AGENTS_FILE_VERSION=$(ls -1t /opt/smartdc/agent-scripts/|grep agents- | grep -v -- "-hvm-" | tail -n1)
AGENTS_FILE_HVM_VERSION=$(ls -1t /opt/smartdc/agent-scripts/|grep agents-hvm- | tail -n1)

echo "Generating agents setup file at '/opt/smartdc/mapi/config/setup_agents.sh'"

cat > /opt/smartdc/mapi-data/setup_agents.sh <<AGENTS
#!/usr/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#

PATH=/usr/bin:/usr/sbin:/bin:/sbin
export PATH

fatal()
{
    # Any error message should be redirected to stderr:
    echo "Error: \$1" 1>&2
    exit 1
}


setup_agents()
{
  cd /var/tmp

  AGENTS_SHAR=\$1

  if [[ -z \${AGENTS_SHAR} ]]; then
    if [[ \$(uname -s) == 'Linux' ]]; then
      AGENTS_SHAR="${AGENTS_FILE_HVM_VERSION}"
    else
      AGENTS_SHAR="${AGENTS_FILE_VERSION}"
    fi
  fi

  /usr/bin/curl --silent --show-error -O http://${PRIVATE_IP}/ur-scripts/\${AGENTS_SHAR}

  if [[ ! -f /var/tmp/\${AGENTS_SHAR} ]]; then
    fatal "failed to download agents setup script"
  fi

  mkdir -p /opt/smartdc/agents/log
  /usr/bin/bash /var/tmp/\${AGENTS_SHAR} &>/opt/smartdc/agents/log/install.log
  result=\$(tail -n 1 /opt/smartdc/agents/log/install.log)

  if [[ "\$result" == "npm not ok" ]]; then
    tail -n 10 /opt/smartdc/agents/log/install.log >&2
    exit 1
  else
    tail -n 10 /opt/smartdc/agents/log/install.log >&2
  fi
}


if [[ ! -d /opt/smartdc/agents/bin ]]; then
  setup_agents \$1
fi

if [[ \$(uname -s) == 'Linux' ]]; then
  # Return SmartDC services statuses on STDOUT:
  initctl list | grep "heartbeater\|provisioner" | sed -e "s/\(.*running\)/online \1/"
else
  # Return SmartDC services statuses on STDOUT:
  echo \$(svcs -a -o STATE,FMRI|grep smartdc)
fi

# Scripts to be executed by Ur need to explicitly return an exit status code:
exit 0

AGENTS



# Generate the reboot server script:

echo "Generating reboot server file at '/opt/smartdc/mapi-data/reboot_server.sh'"

cat > /opt/smartdc/mapi-data/reboot_server.sh <<REBOOT
#!/usr/bin/bash
#
# Copyright (c) 2011 Joyent Inc., All rights reserved.
#

PATH=/usr/bin:/usr/sbin
export PATH

# Scripts to be executed by Ur need to explicitly return an exit status code.
exit 113

REBOOT

# We don't want the setup service if we're upgrading:
if [[ ! -n ${KEEP_DATA_DATASET} ]]; then
  echo "Creating $app_name-setup service"

cat >"/lib/svc/manifest/site/$app_name-setup.xml" <<SETUP_SMF
<?xml version='1.0'?>
<!DOCTYPE service_bundle SYSTEM '/usr/share/lib/xml/dtd/service_bundle.dtd.1'>
<service_bundle type='manifest' name='export'>
  <service name='platform/smartdc/${app_name}-setup' type='service' version='0'>
    <create_default_instance enabled='true'/>
    <single_instance/>
    <dependency name='filesystem' grouping='require_all' restart_on='error' type='service'>
      <service_fmri value='svc:/system/filesystem/local'/>
    </dependency>
    <exec_method name='start' type='method' exec='/opt/smartdc/$app_name-data/$app_name-setup-service.sh' timeout_seconds='180'>
      <method_context>
        <method_credential user='root' group='root'/>
      </method_context>
    </exec_method>
    <exec_method name='stop' type='method' exec=':true' timeout_seconds='0'/>
    <property_group name='application' type='application'/>
    <property_group name='startd' type='framework'>
      <propval name='duration' type='astring' value='transient'/>
    </property_group>
    <stability value='Evolving'/>
    <template>
      <common_name>
        <loctext xml:lang='C'>SmartDC Setup service ($app_name)</loctext>
      </common_name>
    </template>
  </service>
</service_bundle>
SETUP_SMF
fi

cat > "/opt/smartdc/$app_name-data/$app_name-setup-service.sh" <<SETUP_SERVICE
#!/usr/bin/bash

set -o errexit

function fatal
{
    echo "$app_name-setup-service.sh error: \$*"
    echo "Initial data import failed, changing mcp_api service to maintenance status"
    /usr/sbin/svcadm mark -t "maintenance" mcp_api
    exit 1
}

function errexit
{
    [[ \$1 -ne 0 ]] || exit 0
    fatal "error exit status \$1"
}

trap 'errexit \$?' EXIT

POSTGRES_HOST='$POSTGRES_HOST'
POSTGRES_USER='$POSTGRES_USER'
POSTGRES_PW='$POSTGRES_PW'

PGPASSFILE=/opt/smartdc/.pgpass

# This is a workaround.  Normally we would want a proper SMF dependency on the
# postgresql svc, but its too late in the release cycle so we're going to
# hardcode a loop to check the state of the svc here.  We should fix this
# later.
for i in 0 1 2 3 4 5 6 7 8 9
do
    svc=\$(/usr/bin/svcs -H network/postgresql)
    state=\${svc%% * *}
    [ "\$state" == "online" ] && break
    sleep 5
done
# No matter what the state now, we move on.

# Postgres starts out with the default pw of 'postgres'.  We need to change
# it to POSTGRES_PW before we can do anything else.
export PGPASSWORD=postgres
if ! /opt/local/bin/psql -U postgres \
    -c "ALTER USER postgres WITH PASSWORD '$POSTGRES_PW';" template1 ; then
    # We failed to change the pw.  This might happen if we already changed it
    # but the method failed later and we are re-running.  Since we are running
    # with errexit, we need to handle a failure, but we assume the pw is
    # already updated and just note this.
    echo "Changing the default password failed"
fi
export -n PGPASSWORD

# Given PostgreSQL will be into a separated zone, we cannot rely into SMF
# to test DB availability. Need to ping the DB and proceed once we've
# verified we can stablish a connection:

RETRY_AFTER='$DBCONN_RETRY_AFTER' NUM_ATTEMPTS='$DBCONN_NUM_ATTEMPTS' RACK_ENV=production /opt/local/bin/ruby /opt/smartdc/mapi/script/psql-test-connect.rb

if [[ \$? -ne 0 ]]; then
  echo "PostgreSQL not available after ${DBCONN_NUM_ATTEMPTS}, aborting."
  exit 1
else
  echo "Verified PostgreSQL availability, moving forward."
fi

# Without this, mapi db existence checking will always fail:
echo "\$POSTGRES_HOST:*:*:\$POSTGRES_USER:\$POSTGRES_PW" >> /root/.pgpass
chmod 0600 /root/.pgpass

if [[ -z \$(/opt/local/bin/psql -U postgres -h \$POSTGRES_HOST -c "\\l"|grep mapi) ]]; then
  echo "Creating mapi database"
  echo "\$POSTGRES_HOST:*:*:\$POSTGRES_USER:\$POSTGRES_PW" >> /opt/smartdc/.pgpass
  chown jill /opt/smartdc/.pgpass
  chmod 0600 /opt/smartdc/.pgpass
  su - jill -c "/opt/local/bin/createdb -U postgres -h \$POSTGRES_HOST mapi"
fi

echo "Removing hardcoded fastercsv and json_pure dependency on dm-types gem"
\$(/opt/smartdc/mapi/script/apply_gem_patches.sh)

echo "Auto Upgrading MCP API Database."
su - jill -c "cd /opt/smartdc/mapi; RACK_ENV=production /opt/local/bin/rake standalone:db:autoupgrade -f /opt/smartdc/mapi/Rakefile"
sleep 1

# We might be upgrading an older version of MAPI, special fixes here:
if [[ ! -z \$(cat /opt/smartdc/mapi-data/config/config.ru|grep CloudControlApi) ]]; then
  echo "Upgrading MAPI RackUp configuration"
  \$(/opt/local/bin/gsed -i"" -e "s/CloudControlApi/MAPI/" /opt/smartdc/mapi-data/config/config.ru)
fi

if [[ -z \$(/usr/bin/svcs -a|grep mcp_api) ]]; then
  echo "Importing MCP API Unicorn Manifest"
  /usr/sbin/svccfg import /opt/smartdc/mapi/config/unicorn.smf
  sleep 10 # XXX
  #/usr/sbin/svccfg -s svc:/network/smartdc/application/mcp_api:default refresh
fi

if [[ -z \$(/usr/bin/svcs -a|grep provisioner_client) ]]; then
  echo "Importing MCP API Provisioner Client Manifest"
  /usr/sbin/svccfg import /opt/smartdc/mapi/config/provisioner_client.smf
  sleep 10 # XXX
  #/usr/sbin/svccfg -s svc:/network/smartdc/daemon/provisioner_client:default refresh
fi

if [[ -z \$(/usr/bin/svcs -a|grep ur_client) ]]; then
  echo "Importing MAPI Ur Agent Client Manifest"
  /usr/sbin/svccfg import /opt/smartdc/mapi/config/ur_client.smf
  sleep 10 # XXX
  #/usr/sbin/svccfg -s svc:/network/smartdc/daemon/ur_client:default refresh
fi

if [[ -z \$(/usr/bin/svcs -a|grep datasetmanager_client) ]]; then
  echo "Importing MCP API DatasetManager Client Manifest"
  /usr/sbin/svccfg import /opt/smartdc/mapi/config/datasetmanager_client.smf
  sleep 10 # XXX
  #/usr/sbin/svccfg -s svc:/network/smartdc/daemon/datasetmanager_client:default refresh
fi

if [[ -z \$(/usr/bin/svcs -a|grep heartbeater_client) ]]; then
  echo "Importing MCP API Heartbeater Client Manifest"
  /usr/sbin/svccfg import /opt/smartdc/mapi/config/heartbeater_client.smf
  sleep 10 # XXX
  #/usr/sbin/svccfg -s svc:/network/smartdc/daemon/heartbeater_client:default refresh
fi

if [[ -z \$(/usr/bin/svcs -a|grep zonetracker_client) ]]; then
  echo "Importing MCP API ZoneTracker Client Manifest"
  /usr/sbin/svccfg import /opt/smartdc/mapi/config/zonetracker_client.smf
  sleep 10 # XXX
  #/usr/sbin/svccfg -s svc:/network/smartdc/daemon/zonetracker_client:default refresh
fi

## Setup and call the verify script
echo "$POSTGRES_PW" > /tmp/pgpasswd

# (cd /opt/smartdc/mapi && ./script/verify_setup.sh)
(cd /opt/smartdc/mapi && RACK_ENV=production \
    DHCP_RANGE_START="$DHCP_RANGE_START" \
    DHCP_RANGE_END="$DHCP_RANGE_END" \
    ADMIN_NETWORK="$ADMIN_NETWORK" \
    ADMIN_BITCOUNT="$ADMIN_BITCOUNT" \
    ADMIN_GATEWAY="$ADMIN_GATEWAY" \
    ADMIN_IP="$ADMIN_IP" \
    ADMIN_VLAN_ID="$ADMIN_VLAN_ID" \
    EXTERNAL_NETWORK="$EXTERNAL_NETWORK" \
    EXTERNAL_BITCOUNT="$EXTERNAL_BITCOUNT" \
    EXTERNAL_GATEWAY="$EXTERNAL_GATEWAY" \
    EXTERNAL_IP="$EXTERNAL_IP" \
    EXTERNAL_START_IP="$EXTERNAL_START_IP" \
    EXTERNAL_END_IP="$EXTERNAL_END_IP" \
    EXTERNAL_VLAN_ID="$EXTERNAL_VLAN_ID" \
    IMG_TYPE="$IMG_TYPE" \
    COMPANY_NAME="$COMPANY_NAME" \
    LOCATION="$LOCATION" \
    RACK_NAME="$RACK_NAME" \
    RACK_SIZE="$RACK_SIZE" \
    SERVER_ROLE="$SERVER_ROLE" \
    PACKAGE_SIZES="$PACKAGE_SIZES" \
 /opt/local/bin/rake dev:initial_data) 2>&1 | tee /tmp/initial_data.output

if [[ \${PIPESTATUS[0]} -gt 0 ]]; then
  fatal "Initial data import failed, changing mcp_api service to maintenance status"
fi

rm -f /tmp/initial_data.output /tmp/pgpasswd

# Remove the service, we don't wanna run it again (maybe also delete the script?)
echo "Deleting '${app_name}-setup' service"
/usr/sbin/svccfg delete "platform/smartdc/${app_name}-setup"

# Ensure we remove the setup service manifest from this zones core boot manifests
rm /lib/svc/manifest/site/${app_name}-setup.xml

exit 0

SETUP_SERVICE

chmod +x "/opt/smartdc/$app_name-data/$app_name-setup-service.sh"

# Ensure everything in /opt/smartdc is owned by jill
chown -R jill:jill /opt/smartdc

# fix perms on /home
chown root:root /home
chmod 0555 /home

# If we are upgrading, need to restore the DB backup, run migrations and
# import the application services:
if [[ -n ${KEEP_DATA_DATASET} ]]; then

  echo "Removing hardcoded fastercsv and json_pure dependency on dm-types gem"
  $(/opt/smartdc/mapi/script/apply_gem_patches.sh)

  data_version=$(cat /opt/smartdc/${app_name}-data/VERSION)
  dump_file_path=$(ls /opt/smartdc/${app_name}-data/${app_name}-${data_version}*.pg_dump)
  dump_file=$(basename ${dump_file_path%.*})
  db_backup_version=$(echo ${dump_file} | cut -c '6-')

  # Postgres starts out with the default pw of 'postgres'.  We need to change
  # it to POSTGRES_PW before we can do anything else.
  export PGPASSWORD=postgres
  if ! /opt/local/bin/psql -U postgres \
      -c "ALTER USER postgres WITH PASSWORD '$POSTGRES_PW';" template1 ; then
      # We failed to change the pw.  This might happen if we already changed it
      # but the method failed later and we are re-running.  Since we are running
      # with errexit, we need to handle a failure, but we assume the pw is
      # already updated and just note this.
      echo "Changing the default password failed"
  fi
  export -n PGPASSWORD

  if [[ -f ${dump_file_path} ]]; then
    echo "Restoring PostgreSQL DB to previous version"
    VERSION=${db_backup_version} /opt/local/bin/rake pg:restore -f /opt/smartdc/${app_name}/Rakefile
    if [[ $? -gt 0 ]]; then
      echo "FATAL: Unable to restore PostgreSQL Backup. \nPlease, verify DB integrity from the zone and, eventually,\n restore the DB from the file \n'/opt/smartdc/${app_name}-data/${app_name}-${db_backup_version}.pg_dump'."
      exit 1
    fi
  else
    echo "FATAL: Cannot find '${app_name}-${db_backup_version}.pg_dump' on the zone. Unable to restore."
    exit 1
  fi

  echo "Upgrading MCP API Database, running Migrations."
  RACK_ENV=production /opt/local/bin/rake standalone:db:autoupgrade -f /opt/smartdc/${app_name}/Rakefile
  sleep 1

  echo "Importing application services"
  if [[ -z $(/usr/bin/svcs -a|grep mcp_api) ]]; then
    echo "Importing MCP API Unicorn Manifest"
    /usr/sbin/svccfg import /opt/smartdc/${app_name}/config/unicorn.smf
    sleep 10 # XXX
    #/usr/sbin/svccfg -s svc:/network/smartdc/application/mcp_api:default refresh
  fi

  if [[ -z $(/usr/bin/svcs -a|grep provisioner_client) ]]; then
    echo "Importing MCP API Provisioner Client Manifest"
    /usr/sbin/svccfg import /opt/smartdc/${app_name}/config/provisioner_client.smf
    sleep 10 # XXX
    #/usr/sbin/svccfg -s svc:/network/smartdc/daemon/provisioner_client:default refresh
  fi

  if [[ -z $(/usr/bin/svcs -a|grep ur_client) ]]; then
    echo "Importing MAPI Ur Agent Client Manifest"
    /usr/sbin/svccfg import /opt/smartdc/${app_name}/config/ur_client.smf
    sleep 10 # XXX
    #/usr/sbin/svccfg -s svc:/network/smartdc/daemon/ur_client:default refresh
  fi

  if [[ -z $(/usr/bin/svcs -a|grep datasetmanager_client) ]]; then
    echo "Importing MCP API DatasetManager Client Manifest"
    /usr/sbin/svccfg import /opt/smartdc/${app_name}/config/datasetmanager_client.smf
    sleep 10 # XXX
    #/usr/sbin/svccfg -s svc:/network/smartdc/daemon/datasetmanager_client:default refresh
  fi

  if [[ -z $(/usr/bin/svcs -a|grep heartbeater_client) ]]; then
    echo "Importing MCP API Heartbeater Client Manifest"
    /usr/sbin/svccfg import /opt/smartdc/${app_name}/config/heartbeater_client.smf
    sleep 10 # XXX
    #/usr/sbin/svccfg -s svc:/network/smartdc/daemon/heartbeater_client:default refresh
  fi

  if [[ -z $(/usr/bin/svcs -a|grep zonetracker_client) ]]; then
    echo "Importing MCP API ZoneTracker Client Manifest"
    /usr/sbin/svccfg import /opt/smartdc/${app_name}/config/zonetracker_client.smf
    sleep 10 # XXX
    #/usr/sbin/svccfg -s svc:/network/smartdc/daemon/zonetracker_client:default refresh
  fi
fi
