#!/usr/bin/bash
#
# Copyright (c) 2011, Joyent Inc. All rights reserved.
#

export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
set -o xtrace
#set -o errexit

PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

role=sdc
app_name=$role

# This includes the fatal function and downloads and installs files.
source /var/svc/setup.common

# Cookie to identify this as a SmartDC zone and its role
mkdir -p /var/smartdc/sdc

# Add node_modules/bin to PATH
echo "" >>/root/.bashrc
echo "export MANPATH=\${MANPATH}:/opt/smartdc/${role}/man" >>/root/.bashrc
echo "export PATH=\$PATH:/opt/smartdc/$role/bin:/opt/smartdc/$role/build/node/bin:/opt/smartdc/$role/node_modules/.bin" >>/root/.bashrc

# run the configuration
/opt/smartdc/bin/configure || fatal "unable to configure"

touch /var/svc/setup_complete
echo "setup done"
(sleep 5; cp /var/svc/setup.log /var/svc/setup_init.log) &

exit 0
