#!/bin/bash

echo "99 finalizing atropos zone"

# Apply configuration from /opt/smartdc/etc/zoneconfig now
source /opt/smartdc/bin/configure.sh

# Ensure files are owned by the couchdb user
chown -R couchdb:couchdb /var/db/couchdb/ /opt/local/etc/couchdb/

# Setup epmd
if [[ -z $(/usr/bin/svcs -a|grep epmd) ]]; then
  echo "Importing epmd service"
  /usr/sbin/svccfg import /opt/local/share/smf/manifest/epmd.xml
  /usr/sbin/svcadm enable -s epmd
fi

# Import and enable couchdb service
/usr/sbin/svccfg import /opt/local/share/smf/manifest/couchdb.xml
/usr/sbin/svcadm enable -s couchdb

#
# Call mdns_announce (imported from 97-zoneinit-common) to announce our
# service.
#
mdns_announce CouchDB 5984 _npm-registry

